<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BST 260 Introduction to Data Science - 18&nbsp; Inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./19-models.html" rel="next">
<link href="./17-probability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./18-inference.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BST 260 Introduction to Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/datasciencelabs/2023" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course description</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Quarto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-unix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Unix</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Git and GitHub</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-r-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">R Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-vectorization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Vectorization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tidyverse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-dates-and-times.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dates and times</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-importing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Importing data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-data-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">data.table</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pset1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">ggplot2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-dataviz-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data visualization principles</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Wrangling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-web-scraping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Web scraping</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-locales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Locales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-text-mining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Text mining</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pset2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-multivariate-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#parameters-and-estimates" id="toc-parameters-and-estimates" class="nav-link active" data-scroll-target="#parameters-and-estimates"><span class="header-section-number">18.1</span> Parameters and Estimates</a></li>
  <li><a href="#predict-percents-competition" id="toc-predict-percents-competition" class="nav-link" data-scroll-target="#predict-percents-competition"><span class="header-section-number">18.2</span> Predict percents competition</a></li>
  <li><a href="#populations-samples-parameters-and-estimates" id="toc-populations-samples-parameters-and-estimates" class="nav-link" data-scroll-target="#populations-samples-parameters-and-estimates"><span class="header-section-number">18.3</span> Populations, samples, parameters, and estimates</a></li>
  <li><a href="#the-sample-average" id="toc-the-sample-average" class="nav-link" data-scroll-target="#the-sample-average"><span class="header-section-number">18.4</span> The sample average</a></li>
  <li><a href="#clt-in-practice" id="toc-clt-in-practice" class="nav-link" data-scroll-target="#clt-in-practice"><span class="header-section-number">18.5</span> CLT in practice</a>
  <ul class="collapse">
  <li><a href="#a-monte-carlo-simulation" id="toc-a-monte-carlo-simulation" class="nav-link" data-scroll-target="#a-monte-carlo-simulation"><span class="header-section-number">18.5.1</span> A Monte Carlo simulation</a></li>
  </ul></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">18.6</span> Confidence intervals</a>
  <ul class="collapse">
  <li><a href="#a-monte-carlo-simulation-1" id="toc-a-monte-carlo-simulation-1" class="nav-link" data-scroll-target="#a-monte-carlo-simulation-1"><span class="header-section-number">18.6.1</span> A Monte Carlo simulation</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">18.7</span> Exercises</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/datasciencelabs/2023/blob/main/18-inference.qmd" class="toc-action">View source</a></p><p><a href="https://github.com/datasciencelabs/2023/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>The day before the 2008 presidential election, Nate Silver’s FiveThirtyEight stated that</p>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>Barack Obama appears poised for a decisive electoral victory.</p>
</blockquote>
</blockquote>
<p>They went further and predicted that Obama would win the election with 349 electoral votes to 189, and the popular vote by a margin of 6.1%. FiveThirtyEight also attached a probabilistic statement to their prediction claiming that Obama had a 91% chance of winning the election.</p>
<p>Political commentator Joe Scarborough said during <a href="https://www.youtube.com/watch?v=TbKkjm-gheY">his show</a></p>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>Anybody that thinks that this race is anything but a toss-up right now is such an ideologue … they’re jokes.</p>
</blockquote>
</blockquote>
<p>To which Nate Silver responded via Twitter:</p>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>If you think it’s a toss-up, let’s bet. If Obama wins, you donate $1,000 to the American Red Cross. If Romney wins, I do. Deal?</p>
</blockquote>
</blockquote>
<p>In 2016, Silver was not as certain and gave Hillary Clinton only a 71% of winning. In contrast, many other forecasters were almost certain she would win. She lost. But 71% is still more than 50%, so was Mr.&nbsp;Silver wrong? And what does probability mean in this context anyway? Are dice being tossed or cards being dealt somewhere?</p>
<section id="parameters-and-estimates" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="parameters-and-estimates"><span class="header-section-number">18.1</span> Parameters and Estimates</h2>
<p><a href="http://www.realclearpolitics.com">Real Clear Politics</a> is an example of a news aggregator that organizes and publishes poll results. For example, they present the following poll results reporting estimates of the popular vote for the <a href="http://www.realclearpolitics.com/epolls/2016/president/us/general_election_trump_vs_clinton-5491.html">2016 presidential election</a></p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-1_b5480e332a616e796730b3d9f282afd3">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Poll</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Date</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sample</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">MoE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Clinton</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Trump</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Spread</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">RCP Average</td>
<td style="text-align: left;">10/31 - 11/7</td>
<td style="text-align: left;">--</td>
<td style="text-align: left;">--</td>
<td style="text-align: right;">47.2</td>
<td style="text-align: right;">44.3</td>
<td style="text-align: left;">Clinton +2.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bloomberg</td>
<td style="text-align: left;">11/4 - 11/6</td>
<td style="text-align: left;">799 LV</td>
<td style="text-align: left;">3.5</td>
<td style="text-align: right;">46.0</td>
<td style="text-align: right;">43.0</td>
<td style="text-align: left;">Clinton +3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Economist</td>
<td style="text-align: left;">11/4 - 11/7</td>
<td style="text-align: left;">3669 LV</td>
<td style="text-align: left;">--</td>
<td style="text-align: right;">49.0</td>
<td style="text-align: right;">45.0</td>
<td style="text-align: left;">Clinton +4</td>
</tr>
<tr class="even">
<td style="text-align: left;">IBD</td>
<td style="text-align: left;">11/3 - 11/6</td>
<td style="text-align: left;">1026 LV</td>
<td style="text-align: left;">3.1</td>
<td style="text-align: right;">43.0</td>
<td style="text-align: right;">42.0</td>
<td style="text-align: left;">Clinton +1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ABC</td>
<td style="text-align: left;">11/3 - 11/6</td>
<td style="text-align: left;">2220 LV</td>
<td style="text-align: left;">2.5</td>
<td style="text-align: right;">49.0</td>
<td style="text-align: right;">46.0</td>
<td style="text-align: left;">Clinton +3</td>
</tr>
<tr class="even">
<td style="text-align: left;">FOX News</td>
<td style="text-align: left;">11/3 - 11/6</td>
<td style="text-align: left;">1295 LV</td>
<td style="text-align: left;">2.5</td>
<td style="text-align: right;">48.0</td>
<td style="text-align: right;">44.0</td>
<td style="text-align: left;">Clinton +4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monmouth</td>
<td style="text-align: left;">11/3 - 11/6</td>
<td style="text-align: left;">748 LV</td>
<td style="text-align: left;">3.6</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">44.0</td>
<td style="text-align: left;">Clinton +6</td>
</tr>
<tr class="even">
<td style="text-align: left;">CBS News</td>
<td style="text-align: left;">11/2 - 11/6</td>
<td style="text-align: left;">1426 LV</td>
<td style="text-align: left;">3.0</td>
<td style="text-align: right;">47.0</td>
<td style="text-align: right;">43.0</td>
<td style="text-align: left;">Clinton +4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LA Times</td>
<td style="text-align: left;">10/31 - 11/6</td>
<td style="text-align: left;">2935 LV</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: right;">43.0</td>
<td style="text-align: right;">48.0</td>
<td style="text-align: left;">Trump +5</td>
</tr>
<tr class="even">
<td style="text-align: left;">NBC News</td>
<td style="text-align: left;">11/3 - 11/5</td>
<td style="text-align: left;">1282 LV</td>
<td style="text-align: left;">2.7</td>
<td style="text-align: right;">48.0</td>
<td style="text-align: right;">43.0</td>
<td style="text-align: left;">Clinton +5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NBC News</td>
<td style="text-align: left;">10/31 - 11/6</td>
<td style="text-align: left;">30145 LV</td>
<td style="text-align: left;">1.0</td>
<td style="text-align: right;">51.0</td>
<td style="text-align: right;">44.0</td>
<td style="text-align: left;">Clinton +7</td>
</tr>
<tr class="even">
<td style="text-align: left;">McClatchy</td>
<td style="text-align: left;">11/1 - 11/3</td>
<td style="text-align: left;">940 LV</td>
<td style="text-align: left;">3.2</td>
<td style="text-align: right;">46.0</td>
<td style="text-align: right;">44.0</td>
<td style="text-align: left;">Clinton +2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reuters</td>
<td style="text-align: left;">10/31 - 11/4</td>
<td style="text-align: left;">2244 LV</td>
<td style="text-align: left;">2.2</td>
<td style="text-align: right;">44.0</td>
<td style="text-align: right;">40.0</td>
<td style="text-align: left;">Clinton +4</td>
</tr>
<tr class="even">
<td style="text-align: left;">GravisGravis</td>
<td style="text-align: left;">10/31 - 10/31</td>
<td style="text-align: left;">5360 RV</td>
<td style="text-align: left;">1.3</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: left;">Tie</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Let’s make some observations about the table above.</p>
<ul>
<li>Different polls, all taken days before the election, report a different <em>spread</em></li>
<li>Clinton won the popular vote by 2.1%.</li>
<li>We also see a column titled <strong>MoE</strong> which stands for <em>margin of error</em>.</li>
</ul>
</section>
<section id="predict-percents-competition" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="predict-percents-competition"><span class="header-section-number">18.2</span> Predict percents competition</h2>
<p>What percent of the beads are red?</p>
<p><img src="http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/img/urn.jpg" class="img-fluid" style="width:40.0%"></p>
<p>Rules:</p>
<ul>
<li>Winners gets a $25 gift certificate</li>
<li>Provide an estimate and an interval.</li>
<li>If the true percent is not in the interval you are eliminated</li>
<li>Smallest interval wins.</li>
<li>You can take a sample (with replacement) from the urn.</li>
<li>It costs you $0.10 per each bead you sample. Example: if your sample size is 250, and you win, you will break even since you will pay $25 to collect your $25 prize.</li>
</ul>
<p>The <strong>dslabs</strong> package includes a function that shows a random draw from this urn:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="18-inference_files/figure-html/first-simulated-poll-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="populations-samples-parameters-and-estimates" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="populations-samples-parameters-and-estimates"><span class="header-section-number">18.3</span> Populations, samples, parameters, and estimates</h2>
<p>We want to predict the proportion of red beads in the urn. Let’s call this quantity <span class="math inline">\(p\)</span>, which then tells us the proportion of blue beads <span class="math inline">\(1-p\)</span>, and the spread <span class="math inline">\(p - (1-p)\)</span>, which simplifies to <span class="math inline">\(2p - 1\)</span>.</p>
<p>In statistical textbooks:</p>
<ul>
<li>the beads in the urn are called the <em>population</em>.</li>
<li>The proportion of red beads in the population <span class="math inline">\(p\)</span> is called a <em>parameter</em>.</li>
<li>The 25 beads we see in the previous plot are called a <em>sample</em>.</li>
</ul>
<p>The task of statistical inference is to predict the parameter <span class="math inline">\(p\)</span> using the observed data in the sample.</p>
</section>
<section id="the-sample-average" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="the-sample-average"><span class="header-section-number">18.4</span> The sample average</h2>
<p><span class="math display">\[\bar{X} = \frac{1}{N} \sum_{i=1}^N X_i\]</span></p>
<p>Has some desirable properties:</p>
<p><span class="math display">\[
\mbox{E}(\bar{X}) = p
\]</span></p>
<p><span class="math display">\[
\mbox{SE}(\bar{X}) = \sqrt{p(1-p)/N}
\]</span></p>
<p>This result reveals the power of polls. The expected value of the sample proportion <span class="math inline">\(\bar{X}\)</span> is the parameter of interest <span class="math inline">\(p\)</span> and we can make the standard error as small as we want by increasing <span class="math inline">\(N\)</span>. The law of large numbers tells us that with a large enough poll, our estimate converges to <span class="math inline">\(p\)</span>.</p>
<p>Here is the standard error for <span class="math inline">\(p=.25, .5,\)</span> and <span class="math inline">\(0.75\)</span>:</p>
<div class="cell" data-hash="18-inference_cache/html/standard-error-versus-sample-size_ca071878578552a74211830678d41574">
<div class="cell-output-display">
<p><img src="18-inference_files/figure-html/standard-error-versus-sample-size-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the plot we see that we would need a very large polls to get the standarr error below 1%.</p>
<p>But there is one more very useful property based on CLT:</p>
<p><span class="math display">\[
\bar{X} \sim \mbox{Normal}\left(p, \sqrt{p(1-p)/N}\right)
\]</span></p>
</section>
<section id="clt-in-practice" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="clt-in-practice"><span class="header-section-number">18.5</span> CLT in practice</h2>
<p>Now we can ask a more practical questions such as what is the probability that our estimate is within 1% of the actual <span class="math inline">\(p\)</span>. We can write it like this and actually use CLT to answer the question:</p>
<p><span class="math display">\[
\mbox{Pr}(| \bar{X} - p| \leq .01)
\]</span></p>
<p>which is the same as:</p>
<p><span class="math display">\[
\mbox{Pr}(\bar{X} - p\leq  .01) - \mbox{Pr}(\bar{X} - p \leq - .01)
\]</span></p>
<p>we standardize <span class="math inline">\(\bar{X}\)</span> to get a approximately standard normal <span class="math inline">\(Z\)</span>:</p>
<p><span class="math display">\[
\mbox{Pr}\left(Z \leq \frac{ \,.01} {\mbox{SE}(\bar{X})} \right) -
\mbox{Pr}\left(Z \leq - \frac{ \,.01} {\mbox{SE}(\bar{X})} \right)
\]</span></p>
<p>We are almost ready to get a number except since we don’t know <span class="math inline">\(p\)</span>, we don’t know <span class="math inline">\(\mbox{SE}(\bar{X})\)</span>.</p>
<p>But it turns out that the CLT still works if we estimate the standard error by using <span class="math inline">\(\bar{X}\)</span> in place of <span class="math inline">\(p\)</span>. We say that we <em>plug-in</em> the estimate. Our estimate of the standard error is therefore:</p>
<p><span class="math display">\[
\hat{\mbox{SE}}(\bar{X})=\sqrt{\bar{X}(1-\bar{X})/N}
\]</span></p>
<p>Now we continue with our calculation, but dividing by <span class="math inline">\(\hat{\mbox{SE}}(\bar{X})=\sqrt{\bar{X}(1-\bar{X})/N})\)</span> instead. In our first sample we had 12 blue and 13 red so <span class="math inline">\(\bar{X} = 0.52\)</span> and our estimate of standard error is:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-2_10063f49e82f0698aa3f187b4588232f">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x_hat <span class="ot">&lt;-</span> <span class="fl">0.52</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(x_hat<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> x_hat)<span class="sc">/</span><span class="dv">25</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09991997</code></pre>
</div>
</div>
<p>And now we can answer the question of the probability of being close to <span class="math inline">\(p\)</span>. The answer is:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-3_590a4131809f7d151c5248716b556c56">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">0.01</span><span class="sc">/</span>se) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.01</span><span class="sc">/</span>se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07971926</code></pre>
</div>
</div>
<p>Earlier we mentioned the <em>margin of error</em>. Now we can define it because it is simply two times the standard error, which we can now estimate. In our case it is:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-4_a7d42431c6d3e69beaad50e0a1a08054">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fl">1.96</span><span class="sc">*</span>se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1958431</code></pre>
</div>
</div>
<p>Why do we multiply by <span class="math inline">\(1.96 \hat{\mbox{SE}}(\bar{X})\)</span>? Because if you ask what is the probability that we are within 1.96 standard errors from <span class="math inline">\(p\)</span>, we get:</p>
<p><span class="math display">\[
\mbox{Pr}\left(Z \leq \, 1.96\,\hat{\mbox{SE}}(\bar{X})  / \hat{\mbox{SE}}(\bar{X}) \right) -
\mbox{Pr}\left(Z \leq - 1.96\, \hat{\mbox{SE}}(\bar{X}) / \hat{\mbox{SE}}(\bar{X}) \right)
\]</span></p>
<p>which is:</p>
<p><span class="math display">\[
\mbox{Pr}\left(Z \leq 1.96 \right) -
\mbox{Pr}\left(Z \leq - 1.96\right)
\]</span></p>
<p>which we know is about 95%:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-5_34db5e17f4a8f5212012ef45cc4865a8">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.96</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">1.96</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9500042</code></pre>
</div>
</div>
<p>Hence, there is a 95% probability that <span class="math inline">\(\bar{X}\)</span> will be within <span class="math inline">\(1.96\times \hat{SE}(\bar{X})\)</span>, in our case within about 0.2, of <span class="math inline">\(p\)</span>. Note that 95% is somewhat of an arbitrary choice and sometimes other percentages are used, but it is the most commonly used value to define margin of error. We often round 1.96 up to 2 for simplicity of presentation.</p>
<p>In summary, the CLT tells us that our poll based on a sample size of <span class="math inline">\(25\)</span> is not very useful. We don’t really learn much when the margin of error is this large. All we can really say is that the popular vote will not be won by a large margin. This is why pollsters tend to use larger sample sizes.</p>
<section id="a-monte-carlo-simulation" class="level3" data-number="18.5.1">
<h3 data-number="18.5.1" class="anchored" data-anchor-id="a-monte-carlo-simulation"><span class="header-section-number">18.5.1</span> A Monte Carlo simulation</h3>
<p>Suppose we want to use a Monte Carlo simulation to corroborate the tools we have built using probability theory. To create the simulation, we would write code like this:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-6_d14fe466cc97c6ab60f0fefe02048b17">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.45</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>x_hat <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, {</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">-</span>p, p))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(x)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The problem is, of course, we don’t know <code>p</code>. We could construct an urn like the one pictured above and run an analog (without a computer) simulation. It would take a long time, but you could take 10,000 samples, count the beads and keep track of the proportions of blue. We can use the function <code>take_poll(n=1000)</code> instead of drawing from an actual urn, but it would still take time to count the beads and enter the results.</p>
<p>One thing we therefore do to corroborate theoretical results is to pick one or several values of <code>p</code> and run the simulations. Let’s set <code>p=0.45</code>. We can then simulate a poll:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-7_24dd2355296a317351ec6ccc79e29f95">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.45</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> p, p))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>x_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this particular sample, our estimate is <code>x_hat</code>. We can use that code to do a Monte Carlo simulation:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-8_9852ae7d95ce17f973af3981043d1a5c">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>x_hat <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, {</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> p, p))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(x)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To review, the theory tells us that <span class="math inline">\(\bar{X}\)</span> is approximately normally distributed, has expected value <span class="math inline">\(p=\)</span> 0.45 and standard error <span class="math inline">\(\sqrt{p(1-p)/N}\)</span> = 0.0157321. The simulation confirms this:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-9_c9b845328d03bfcd7dea37a4feb2ff32">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x_hat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4500729</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>((x_hat<span class="sc">-</span><span class="fu">mean</span>(x_hat))<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0002484474</code></pre>
</div>
</div>
<p>A histogram and qq-plot confirm that the normal approximation is accurate as well:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="18-inference_files/figure-html/normal-approximation-for-polls-1.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>Of course, in real life we would never be able to run such an experiment because we don’t know <span class="math inline">\(p\)</span>. But we could run it for various values of <span class="math inline">\(p\)</span> and <span class="math inline">\(N\)</span> and see that the theory does indeed work well for most values. You can easily do this by re-running the code above after changing <code>p</code> and <code>N</code>.</p>
</section>
</section>
<section id="confidence-intervals" class="level2" data-number="18.6">
<h2 data-number="18.6" class="anchored" data-anchor-id="confidence-intervals"><span class="header-section-number">18.6</span> Confidence intervals</h2>
<p>We want to know the probability that the interval</p>
<p><span class="math display">\[
[\bar{X} - 1.96\hat{\mbox{SE}}(\bar{X}), \bar{X} + 1.96\hat{\mbox{SE}}(\bar{X})]
\]</span></p>
<p>contains the true proportion <span class="math inline">\(p\)</span>. First, consider that the start and end of these intervals are random variables: every time we take a sample, they change. To illustrate this, run the Monte Carlo simulation above twice. We use the same parameters as above:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-10_2240048ebd8c3350abb11e1bf5b22708">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.45</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And notice that the interval here:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-11_9540bd8268c2aa56de8c9b98dce19979">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> p, p))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>x_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>se_hat <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(x_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> x_hat) <span class="sc">/</span> N)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>x_hat <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)<span class="sc">*</span>se_hat <span class="sc">*</span> <span class="fl">1.96</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4420549 0.5039451</code></pre>
</div>
</div>
<p>is different from this one:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-12_887fdc5c860bff2e67388a328da2ca22">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> p, p))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>x_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>se_hat <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(x_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> x_hat) <span class="sc">/</span> N)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(x_hat <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_hat, x_hat <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_hat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3993149 0.4606851</code></pre>
</div>
</div>
<p>Keep sampling and creating intervals and you will see the random variation.</p>
<p>To determine the probability that the interval includes <span class="math inline">\(p\)</span>, we need to compute this:</p>
<p><span class="math display">\[
\mbox{Pr}\left(\bar{X} - 1.96\hat{\mbox{SE}}(\bar{X}) \leq p \leq \bar{X} + 1.96\hat{\mbox{SE}}(\bar{X})\right)
\]</span></p>
<p>By subtracting and dividing the same quantities in all parts of the equation, we get that the above is equivalent to:</p>
<p><span class="math display">\[
\mbox{Pr}\left(-1.96 \leq \frac{\bar{X}- p}{\hat{\mbox{SE}}(\bar{X})} \leq  1.96\right)
\]</span></p>
<p>The term in the middle is an approximately normal random variable with expected value 0 and standard error 1, which we have been denoting with <span class="math inline">\(Z\)</span>, so we have:</p>
<p><span class="math display">\[
\mbox{Pr}\left(-1.96 \leq Z \leq  1.96\right)
\]</span></p>
<p>which we can quickly compute using :</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-13_b139c38de6588ac8989608b00c8b6434">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.96</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">1.96</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9500042</code></pre>
</div>
</div>
<p>proving that we have a 95% probability.</p>
<p>If we want to have a larger probability, say 99%, we need to multiply by whatever <code>z</code> satisfies the following:</p>
<p><span class="math display">\[
\mbox{Pr}\left(-z \leq Z \leq  z\right) = 0.99
\]</span></p>
<p>Using:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-14_13d158e95d34066db06d4a9fa93359c9">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.995</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>z</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.575829</code></pre>
</div>
</div>
<p>will achieve this because by definition <code>pnorm(qnorm(0.995))</code> is 0.995 and by symmetry <code>pnorm(1-qnorm(0.995))</code> is 1 - 0.995. As a consequence, we have that:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-15_a79ead7dcd7c788b78b44bcfecaee508">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(z) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span>z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.99</code></pre>
</div>
</div>
<p>is <code>0.995 - 0.005 = 0.99</code>.</p>
<p>We can use this approach for any probability, not just 0.95 and 0.99. In statistics textbooks, these are usually written for any probability as <span class="math inline">\(1-\alpha\)</span>. We can then obtain the <span class="math inline">\(z\)</span> for the equation above noting using <code>z = qnorm(1 - alpha / 2)</code> because <span class="math inline">\(1 - \alpha/2 - \alpha/2 = 1 - \alpha\)</span>.</p>
<p>So, for example, for <span class="math inline">\(\alpha=0.05\)</span>, <span class="math inline">\(1 - \alpha/2 = 0.975\)</span> and we get the 1.96 we have been using:</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-16_95b219704966bcfc2ded658b42ed9f08">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<section id="a-monte-carlo-simulation-1" class="level3" data-number="18.6.1">
<h3 data-number="18.6.1" class="anchored" data-anchor-id="a-monte-carlo-simulation-1"><span class="header-section-number">18.6.1</span> A Monte Carlo simulation</h3>
<p>We can run a Monte Carlo simulation to confirm that, in fact, a 95% confidence interval includes <span class="math inline">\(p\)</span> 95% of the time.</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-18_9d2d38c667d63838f5186d898ac7da17">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>inside <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, {</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> p, p))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  x_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  se_hat <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(x_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> x_hat) <span class="sc">/</span> N)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">between</span>(p, x_hat <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_hat, x_hat <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_hat)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(inside)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9482</code></pre>
</div>
</div>
<p>The following plot shows the first 100 confidence intervals. In this case, we created the simulation so the black line denotes the parameter we are trying to estimate:</p>
<div class="cell" data-hash="18-inference_cache/html/confidence-interval-coverage_367c64e66d29d69b81f3c3c5b46beff6">
<div class="cell-output-display">
<p><img src="18-inference_files/figure-html/confidence-interval-coverage-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="exercises" class="level2" data-number="18.7">
<h2 data-number="18.7" class="anchored" data-anchor-id="exercises"><span class="header-section-number">18.7</span> Exercises</h2>
<ol class="example" type="1">
<li><p>Write a line of code that gives you the standard error <code>se</code> for the proportion of red beads for several values of <span class="math inline">\(p\)</span>, specifically for <code>p &lt;- seq(0, 1, length = 100)</code>. Make a plot of <code>se</code> versus <code>p</code>.</p></li>
<li><p>If we are interested in the difference in proportions, <span class="math inline">\(\mu = p - (1-p)\)</span>, our estimate is <span class="math inline">\(\hat{\mu} = \bar{X} - (1-\bar{X})\)</span> expected value and SE of <span class="math inline">\(\hat{\mu}\)</span>.</p></li>
<li><p>If the actual <span class="math inline">\(p=.45\)</span>, it means the Republicans are winning by a relatively large margin since <span class="math inline">\(\mu = -.1\)</span>, which is a 10% margin of victory. In this case, what is the standard error of <span class="math inline">\(2\hat{X}-1\)</span> if we take a sample of <span class="math inline">\(N=25\)</span>?</p></li>
<li><p>Given the answer to 9, which of the following best describes your strategy of using a sample size of <span class="math inline">\(N=25\)</span>?</p></li>
</ol>
<ol type="a">
<li>The expected value of our estimate <span class="math inline">\(2\bar{X}-1\)</span> is <span class="math inline">\(\mu\)</span>, so our prediction will be right on.</li>
<li>Our standard error is larger than the difference, so the chances of <span class="math inline">\(2\bar{X}-1\)</span> being positive and throwing us off were not that small. We should pick a larger sample size.</li>
<li>The difference is 10% and the standard error is about 0.2, therefore much smaller than the difference.</li>
<li>Because we don’t know <span class="math inline">\(p\)</span>, we have no way of knowing that making <span class="math inline">\(N\)</span> larger would actually improve our standard error.</li>
</ol>
<p>For the next exercises, we will use actual polls from the 2016 election. You can load the data from the <strong>dslabs</strong> package.</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-19_74f6a7acdad28fe095c1998e3bb299f0">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Specifically, we will use all the national polls that ended within one week before the election.</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-20_cdfa1eb2418b25a6ab9032039eb623dc">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>polls <span class="ot">&lt;-</span> polls_us_election_2016 <span class="sc">|&gt;</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(enddate <span class="sc">&gt;=</span> <span class="st">"2016-10-31"</span> <span class="sc">&amp;</span> state <span class="sc">==</span> <span class="st">"U.S."</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="5" class="example" type="1">
<li>For the first poll, you can obtain the samples size and estimated Clinton percentage with:</li>
</ol>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-21_ca78b6b0ed1934879098ce16bc100a46">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> polls<span class="sc">$</span>samplesize[<span class="dv">1</span>]</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>x_hat <span class="ot">&lt;-</span> polls<span class="sc">$</span>rawpoll_clinton[<span class="dv">1</span>]<span class="sc">/</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Assume there are only two candidates and construct a 95% confidence interval for the election night proportion <span class="math inline">\(p\)</span>.</p>
<ol start="6" class="example" type="1">
<li><p>Now use <code>dplyr</code> to add a confidence interval as two columns, call them <code>lower</code> and <code>upper</code>, to the object <code>poll</code>. Then use <code>select</code> to show the <code>pollster</code>, <code>enddate</code>, <code>x_hat</code>,<code>lower</code>, <code>upper</code> variables. Hint: define temporary columns <code>x_hat</code> and <code>se_hat</code>.</p></li>
<li><p>The final tally for the popular vote was Clinton 48.2% and Trump 46.1%. Add a column, call it <code>hit</code>, to the previous table stating if the confidence interval included the true proportion <span class="math inline">\(p=0.482\)</span> or not.</p></li>
<li><p>For the table you just created, what proportion of confidence intervals included <span class="math inline">\(p\)</span>?</p></li>
<li><p>If these confidence intervals are constructed correctly, and the theory holds up, what proportion should include <span class="math inline">\(p\)</span>?</p></li>
</ol>
<p>(@). A much smaller proportion of the polls than expected produce confidence intervals containing <span class="math inline">\(p\)</span>. If you look closely at the table, you will see that most polls that fail to include <span class="math inline">\(p\)</span> are underestimating. The reason for this is undecided voters, individuals polled that do not yet know who they will vote for or do not want to say. Because, historically, undecideds divide evenly between the two main candidates on election day, it is more informative to estimate the spread or the difference between the proportion of two candidates <span class="math inline">\(\mu\)</span>, which in this election was <span class="math inline">\(0. 482 - 0.461 = 0.021\)</span>. Assume that there are only two parties and that <span class="math inline">\(\mu = 2p - 1\)</span>, redefine <code>polls</code> as below and re-do exercise 1, but for the difference.</p>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-22_61cbadf86c31895df0519e6ef1bf1782">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>polls <span class="ot">&lt;-</span> polls_us_election_2016 <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(enddate <span class="sc">&gt;=</span> <span class="st">"2016-10-31"</span> <span class="sc">&amp;</span> state <span class="sc">==</span> <span class="st">"U.S."</span>)  <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mu_hat =</span> rawpoll_clinton <span class="sc">/</span> <span class="dv">100</span> <span class="sc">-</span> rawpoll_trump <span class="sc">/</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="10" class="example" type="1">
<li>Now recalculate confidence interavls for the difference and see how often the polls include the election night difference of 0.21.</li>
</ol>
<div class="cell" data-hash="18-inference_cache/html/unnamed-chunk-23_76ca82a83902c47d025d8b02bc763cd1">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>polls <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">p =</span> (mu_hat <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">/</span><span class="dv">2</span>, <span class="at">se =</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(p<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p))<span class="sc">/</span><span class="fu">sqrt</span>(samplesize)) <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lower =</span> mu_hat <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>se, <span class="at">upper =</span> mu_hat <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   state  startdate    enddate
1   U.S. 2016-11-03 2016-11-06
2   U.S. 2016-11-01 2016-11-07
3   U.S. 2016-11-02 2016-11-06
4   U.S. 2016-11-04 2016-11-07
5   U.S. 2016-11-03 2016-11-06
6   U.S. 2016-11-03 2016-11-06
7   U.S. 2016-11-02 2016-11-06
8   U.S. 2016-11-03 2016-11-05
9   U.S. 2016-11-04 2016-11-07
10  U.S. 2016-11-04 2016-11-06
11  U.S. 2016-11-01 2016-11-04
12  U.S. 2016-11-03 2016-11-06
13  U.S. 2016-11-01 2016-11-03
14  U.S. 2016-11-05 2016-11-07
15  U.S. 2016-11-01 2016-11-07
16  U.S. 2016-11-01 2016-11-05
17  U.S. 2016-10-31 2016-11-06
18  U.S. 2016-11-04 2016-11-05
19  U.S. 2016-10-31 2016-11-06
20  U.S. 2016-11-02 2016-11-06
21  U.S. 2016-11-04 2016-11-07
22  U.S. 2016-10-20 2016-11-01
23  U.S. 2016-11-01 2016-11-03
24  U.S. 2016-10-28 2016-11-01
25  U.S. 2016-11-02 2016-11-05
26  U.S. 2016-10-31 2016-11-04
27  U.S. 2016-11-01 2016-11-04
28  U.S. 2016-10-04 2016-11-06
29  U.S. 2016-11-03 2016-11-06
30  U.S. 2016-10-31 2016-11-03
31  U.S. 2016-10-30 2016-11-03
32  U.S. 2016-11-02 2016-11-05
33  U.S. 2016-10-30 2016-11-02
34  U.S. 2016-10-29 2016-11-01
35  U.S. 2016-10-28 2016-10-31
36  U.S. 2016-10-30 2016-11-03
37  U.S. 2016-11-01 2016-11-04
38  U.S. 2016-10-30 2016-11-01
39  U.S. 2016-10-26 2016-10-31
40  U.S. 2016-10-29 2016-11-02
41  U.S. 2016-11-01 2016-11-03
42  U.S. 2016-11-04 2016-11-06
43  U.S. 2016-10-28 2016-11-01
44  U.S. 2016-10-29 2016-11-02
45  U.S. 2016-10-28 2016-11-01
46  U.S. 2016-10-31 2016-11-02
47  U.S. 2016-10-27 2016-10-31
48  U.S. 2016-11-03 2016-11-05
49  U.S. 2016-10-27 2016-10-31
50  U.S. 2016-10-25 2016-10-31
51  U.S. 2016-10-30 2016-11-05
52  U.S. 2016-10-30 2016-11-01
53  U.S. 2016-10-29 2016-11-04
54  U.S. 2016-11-02 2016-11-04
55  U.S. 2016-10-31 2016-11-06
56  U.S. 2016-10-28 2016-11-03
57  U.S. 2016-11-01 2016-11-03
58  U.S. 2016-10-30 2016-11-05
59  U.S. 2016-10-27 2016-11-02
60  U.S. 2016-10-29 2016-11-04
61  U.S. 2016-10-26 2016-11-01
62  U.S. 2016-10-31 2016-11-02
63  U.S. 2016-10-31 2016-10-31
64  U.S. 2016-10-28 2016-11-03
65  U.S. 2016-10-30 2016-11-01
66  U.S. 2016-10-27 2016-11-02
67  U.S. 2016-11-01 2016-11-02
68  U.S. 2016-10-26 2016-11-01
69  U.S. 2016-10-29 2016-10-31
70  U.S. 2016-10-25 2016-10-31
                                                     pollster grade samplesize
1                                    ABC News/Washington Post    A+       2220
2                                     Google Consumer Surveys     B      26574
3                                                       Ipsos    A-       2195
4                                                      YouGov     B       3677
5                                            Gravis Marketing    B-      16639
6  Fox News/Anderson Robbins Research/Shaw &amp; Company Research     A       1295
7                                     CBS News/New York Times    A-       1426
8                                NBC News/Wall Street Journal    A-       1282
9                                                    IBD/TIPP    A-       1107
10                                           Selzer &amp; Company    A+        799
11                                          Angus Reid Global    A-       1151
12                                        Monmouth University    A+        748
13                                             Marist College     A        940
14                                   The Times-Picayune/Lucid  &lt;NA&gt;       2521
15                                      USC Dornsife/LA Times  &lt;NA&gt;       2972
16                      RKM Research and Communications, Inc.    B+       1009
17                                       CVOTER International    C+       1625
18                                            Morning Consult  &lt;NA&gt;       1482
19                                               SurveyMonkey    C-      70194
20                   Rasmussen Reports/Pulse Opinion Research    C+       1500
21                                              Insights West  &lt;NA&gt;        940
22                                 RAND (American Life Panel)    B-       2269
23 Fox News/Anderson Robbins Research/Shaw &amp; Company Research     A       1107
24                                    CBS News/New York Times    A-        927
25                                   ABC News/Washington Post    A+       1937
26                                                      Ipsos    A-       2244
27                                   ABC News/Washington Post    A+       1685
28                                                     YouGov     B      84292
29                                                   IBD/TIPP    A-       1026
30                                   ABC News/Washington Post    A+       1419
31                                                   IBD/TIPP    A-        898
32                                                   IBD/TIPP    A-        903
33                                   ABC News/Washington Post    A+       1151
34                                   ABC News/Washington Post    A+       1167
35                                   ABC News/Washington Post    A+       1182
36                                                      Ipsos    A-       2021
37                                                   IBD/TIPP    A-        804
38                                                     YouGov     B       1233
39                                                   IBD/TIPP    A-       1018
40                                                      Ipsos    A-       1922
41                   Rasmussen Reports/Pulse Opinion Research    C+       1500
42                                   The Times-Picayune/Lucid  &lt;NA&gt;       2584
43                                                      Ipsos    A-       1772
44                                                   IBD/TIPP    A-        867
45                                                   IBD/TIPP    A-        862
46                   Rasmussen Reports/Pulse Opinion Research    C+       1500
47                                                      Ipsos    A-       1464
48                                   The Times-Picayune/Lucid  &lt;NA&gt;       2526
49                   Rasmussen Reports/Pulse Opinion Research    C+       1500
50                                    Google Consumer Surveys     B      24316
51                                       CVOTER International    C+       1572
52                   Rasmussen Reports/Pulse Opinion Research    C+       1500
53                                       CVOTER International    C+       1479
54                                   The Times-Picayune/Lucid  &lt;NA&gt;       2561
55                                      USC Dornsife/LA Times  &lt;NA&gt;       2935
56                                       CVOTER International    C+       1395
57                                   The Times-Picayune/Lucid  &lt;NA&gt;       2627
58                                      USC Dornsife/LA Times  &lt;NA&gt;       2988
59                                       CVOTER International    C+       1329
60                                      USC Dornsife/LA Times  &lt;NA&gt;       2987
61                                       CVOTER International    C+       1383
62                                   The Times-Picayune/Lucid  &lt;NA&gt;       2620
63                                           Gravis Marketing    B-       5360
64                                      USC Dornsife/LA Times  &lt;NA&gt;       2962
65                                   The Times-Picayune/Lucid  &lt;NA&gt;       2617
66                                      USC Dornsife/LA Times  &lt;NA&gt;       2938
67                                           Gravis Marketing    B-       2435
68                                      USC Dornsife/LA Times  &lt;NA&gt;       3004
69                                   The Times-Picayune/Lucid  &lt;NA&gt;       2600
70                                      USC Dornsife/LA Times  &lt;NA&gt;       3145
   population rawpoll_clinton rawpoll_trump rawpoll_johnson rawpoll_mcmullin
1          lv           47.00         43.00            4.00               NA
2          lv           38.03         35.69            5.46               NA
3          lv           42.00         39.00            6.00               NA
4          lv           45.00         41.00            5.00               NA
5          rv           47.00         43.00            3.00               NA
6          lv           48.00         44.00            3.00               NA
7          lv           45.00         41.00            5.00               NA
8          lv           44.00         40.00            6.00               NA
9          lv           41.20         42.70            7.10               NA
10         lv           44.00         41.00            4.00               NA
11         lv           48.00         44.00            6.00               NA
12         lv           50.00         44.00            4.00               NA
13         lv           44.00         43.00            6.00               NA
14         lv           45.00         40.00            5.00               NA
15         lv           43.61         46.84              NA               NA
16         lv           47.60         44.40            4.30               NA
17         lv           48.91         46.13              NA               NA
18         lv           45.00         42.00            8.00               NA
19         lv           47.00         41.00            6.00               NA
20         lv           45.00         43.00            4.00               NA
21         lv           49.00         45.00            4.00               NA
22         lv           43.70         34.60            7.70               NA
23         lv           45.50         44.00            5.00               NA
24         lv           45.00         42.00            5.00               NA
25         lv           47.00         43.00            4.00               NA
26         lv           43.00         39.00            6.00               NA
27         lv           48.00         43.00            4.00               NA
28         lv           42.90         39.00            4.70               NA
29         lv           40.70         43.10            6.30               NA
30         lv           47.00         43.00            4.00               NA
31         lv           44.40         43.90            3.70               NA
32         lv           43.00         44.00            5.00               NA
33         lv           47.00         44.00            3.00               NA
34         lv           47.00         45.00            3.00               NA
35         lv           46.00         46.00            3.00               NA
36         lv           43.20         38.30            5.90               NA
37         lv           44.20         43.70            4.80               NA
38         lv           46.00         43.00            4.00               NA
39         lv           44.60         43.70            4.20               NA
40         lv           45.50         37.30            5.40               NA
41         lv           44.00         44.00            4.00               NA
42         lv           45.00         40.00            5.00               NA
43         lv           44.70         37.40            5.30               NA
44         lv           44.00         44.10            3.90               NA
45         lv           44.00         44.40            4.10               NA
46         lv           42.00         45.00            4.00               NA
47         lv           44.00         37.20            5.90               NA
48         lv           45.00         40.00            5.00               NA
49         lv           44.00         44.00            5.00               NA
50         lv           37.69         35.07            6.18               NA
51         lv           49.25         45.92              NA               NA
52         lv           44.00         44.00            5.00               NA
53         lv           49.06         47.82              NA               NA
54         lv           45.00         39.00            5.00               NA
55         lv           43.23         47.98              NA               NA
56         lv           48.53         48.44              NA               NA
57         lv           44.00         39.00            6.00               NA
58         lv           42.63         48.16              NA               NA
59         lv           48.78         48.22              NA               NA
60         lv           42.56         47.96              NA               NA
61         lv           48.81         48.14              NA               NA
62         lv           44.00         39.00            6.00               NA
63         rv           46.00         45.00            4.00               NA
64         lv           43.38         46.89              NA               NA
65         lv           43.00         40.00            6.00               NA
66         lv           42.47         47.50              NA               NA
67         rv           47.00         45.00            3.00               NA
68         lv           42.36         47.83              NA               NA
69         lv           42.00         40.00            5.00               NA
70         lv           43.28         46.90              NA               NA
   adjpoll_clinton adjpoll_trump adjpoll_johnson adjpoll_mcmullin  mu_hat
1         45.20163      41.72430        4.626221               NA  0.0400
2         43.34557      41.21439        5.175792               NA  0.0234
3         42.02638      38.81620        6.844734               NA  0.0300
4         45.65676      40.92004        6.069454               NA  0.0400
5         46.84089      42.33184        3.726098               NA  0.0400
6         49.02208      43.95631        3.057876               NA  0.0400
7         45.11649      40.92722        4.341786               NA  0.0400
8         43.58576      40.77325        5.365788               NA  0.0400
9         42.92745      42.23545        6.316175               NA -0.0150
10        44.21714      40.57082        4.068708               NA  0.0300
11        47.57171      43.68125        5.556625               NA  0.0400
12        48.86765      43.39600        4.838600               NA  0.0600
13        42.83406      43.43819        4.780429               NA  0.0100
14        45.13966      42.26495        3.679914               NA  0.0500
15        45.32156      43.38579              NA               NA -0.0323
16        47.63973      43.16080        4.761112               NA  0.0320
17        47.01806      42.04561              NA               NA  0.0278
18        46.28310      43.27167        6.904304               NA  0.0300
19        45.65592      40.37888        3.677361               NA  0.0600
20        45.56041      43.13745        4.418502               NA  0.0200
21        49.14547      45.12675        4.253578               NA  0.0400
22        43.13676      38.24491        5.957800               NA  0.0910
23        46.70731      44.14856        4.979693               NA  0.0150
24        45.23948      42.55291        3.928672               NA  0.0300
25        45.28374      41.76419        4.635295               NA  0.0400
26        43.12950      38.96855        6.757478               NA  0.0400
27        46.34620      41.81491        4.620226               NA  0.0500
28        43.74084      41.38541        4.411561               NA  0.0390
29        42.51610      42.67482        5.607142               NA -0.0240
30        45.38686      41.91655        4.548039               NA  0.0400
31        46.41406      43.79416        2.837214               NA  0.0050
32        44.89821      43.61472        4.316216               NA -0.0100
33        45.39959      43.04363        3.456292               NA  0.0300
34        45.40490      44.19081        3.354964               NA  0.0200
35        44.40672      45.38988        3.222180               NA  0.0000
36        43.34223      38.39563        6.565732               NA  0.0490
37        46.16068      43.36544        4.101147               NA  0.0050
38        46.94868      43.42593        4.889163               NA  0.0300
39        46.61572      44.16262        2.969010               NA  0.0090
40        45.64754      37.54281        5.964403               NA  0.0820
41        44.66353      44.28981        4.331246               NA  0.0000
42        45.22830      42.30433        3.770880               NA  0.0500
43        44.84936      37.84188        5.731620               NA  0.0730
44        46.01937      44.14133        2.935885               NA -0.0010
45        46.02119      44.64041        3.003101               NA -0.0040
46        42.67626      45.41689        4.239500               NA -0.0300
47        44.14389      37.86409        6.197528               NA  0.0680
48        45.31041      42.34422        3.779955               NA  0.0500
49        44.67792      44.98535        4.871296               NA  0.0000
50        43.11401      41.64819        5.238244               NA  0.0262
51        47.36662      41.90514              NA               NA  0.0333
52        44.68157      44.56407        5.138172               NA  0.0000
53        47.15442      43.89729              NA               NA  0.0124
54        45.37288      41.39494        3.764886               NA  0.0600
55        44.98547      44.55796              NA               NA -0.0475
56        46.59161      44.62636              NA               NA  0.0009
57        44.41354      41.49658        4.692698               NA  0.0500
58        44.39404      44.80749              NA               NA -0.0553
59        46.79931      44.56131              NA               NA  0.0056
60        44.30183      44.69964              NA               NA -0.0540
61        46.77929      44.65897              NA               NA  0.0067
62        44.42627      41.62366        4.600952               NA  0.0500
63        46.04416      44.79836        4.454841               NA  0.0100
64        45.08903      43.73871              NA               NA -0.0351
65        43.43158      42.77084        4.499624               NA  0.0300
66        44.13673      44.50366              NA               NA -0.0503
67        47.02612      44.52409        3.647916               NA  0.0200
68        43.97671      45.01132              NA               NA -0.0547
69        42.43340      42.96991        3.366840               NA  0.0200
70        44.84075      44.24033              NA               NA -0.0362
         p          se        lower         upper
1  0.52000 0.021206832 -0.001565391  0.0815653910
2  0.51170 0.006132712  0.011379884  0.0354201164
3  0.51500 0.021334733 -0.011816077  0.0718160772
4  0.52000 0.016478037  0.007703048  0.0722969523
5  0.52000 0.007746199  0.024817449  0.0551825509
6  0.52000 0.027766261 -0.014421872  0.0944218716
7  0.52000 0.026460164 -0.011861920  0.0918619205
8  0.52000 0.027906686 -0.014697106  0.0946971055
9  0.49250 0.030052273 -0.073902455  0.0439024552
10 0.51500 0.035361533 -0.039308606  0.0993086056
11 0.52000 0.029451989 -0.017725898  0.0977258977
12 0.53000 0.036497747 -0.011535585  0.1315355848
13 0.50500 0.032614773 -0.053924955  0.0739249547
14 0.52500 0.019891614  0.011012436  0.0889875640
15 0.48385 0.018333650 -0.068233954  0.0036339536
16 0.51600 0.031465305 -0.029671998  0.0936719976
17 0.51390 0.024797359 -0.020802824  0.0764028240
18 0.51500 0.025964525 -0.020890468  0.0808904685
19 0.53000 0.003767618  0.052615469  0.0673845313
20 0.51000 0.025814724 -0.030596860  0.0705968600
21 0.52000 0.032590300 -0.023876988  0.1038769882
22 0.54550 0.020906295  0.050023662  0.1319763377
23 0.50750 0.030052273 -0.043902455  0.0739024552
24 0.51500 0.032829526 -0.034345871  0.0943458710
25 0.52000 0.022703221 -0.004498313  0.0844983131
26 0.52000 0.021093122 -0.001342519  0.0813425187
27 0.52500 0.024330806  0.002311620  0.0976883802
28 0.51950 0.003441726  0.032254217  0.0457457829
29 0.48800 0.031210535 -0.085172648  0.0371726477
30 0.52000 0.026525348 -0.011989682  0.0919896819
31 0.50250 0.033370015 -0.060405230  0.0704052296
32 0.49500 0.033276252 -0.075221455  0.0552214546
33 0.51500 0.029462312 -0.027746131  0.0877461306
34 0.51000 0.029266966 -0.037363252  0.0773632524
35 0.50000 0.029086486 -0.057009513  0.0570095133
36 0.52450 0.022217482  0.005453734  0.0925462656
37 0.50250 0.035266840 -0.064123006  0.0741230063
38 0.51500 0.028465770 -0.025792910  0.0857929099
39 0.50450 0.031340688 -0.052427748  0.0704277478
40 0.54100 0.022733080  0.037443163  0.1265568367
41 0.50000 0.025819889 -0.050606982  0.0506069824
42 0.52500 0.019647631  0.011490643  0.0885093572
43 0.53650 0.023692335  0.026563023  0.1194369771
44 0.49950 0.033961764 -0.067565057  0.0655650566
45 0.49800 0.034059863 -0.070757331  0.0627573309
46 0.48500 0.025808267 -0.080584204  0.0205842041
47 0.53400 0.026074924  0.016893150  0.1191068502
48 0.52500 0.019871918  0.011051041  0.0889489586
49 0.50000 0.025819889 -0.050606982  0.0506069824
50 0.51310 0.006410691  0.013635046  0.0387649537
51 0.51665 0.025207676 -0.016107044  0.0827070444
52 0.50000 0.025819889 -0.050606982  0.0506069824
53 0.50620 0.026000549 -0.038561076  0.0633610765
54 0.53000 0.019724776  0.021339440  0.0986605601
55 0.47625 0.018437645 -0.083637785 -0.0113622153
56 0.50045 0.026773967 -0.051576975  0.0533769749
57 0.52500 0.019486167  0.011807113  0.0881928869
58 0.47235 0.018266049 -0.091101457 -0.0194985430
59 0.50280 0.027430309 -0.048163406  0.0593634056
60 0.47300 0.018270409 -0.089810001 -0.0181899990
61 0.50335 0.026889279 -0.046002987  0.0594029874
62 0.52500 0.019512181  0.011756126  0.0882438739
63 0.50500 0.013658276 -0.016770221  0.0367702213
64 0.48245 0.018362837 -0.071091161  0.0008911606
65 0.51500 0.019539013 -0.008296465  0.0682964652
66 0.47485 0.018425700 -0.086414373 -0.0141856272
67 0.51000 0.020261129 -0.019711813  0.0597118128
68 0.47265 0.018217943 -0.090407168 -0.0189928318
69 0.51000 0.019607691 -0.018431074  0.0584310740
70 0.48190 0.017819886 -0.071126977 -0.0012730227</code></pre>
</div>
</div>
<ol start="11" class="example" type="1">
<li><p>Make a plot of the error, the difference between each poll’s estimate and the actual <span class="math inline">\(mu=0.021\)</span> stratified by pollster.</p></li>
<li><p>Redo the previous plot but only for pollsters that took five or more polls.</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./17-probability.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Probability</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./19-models.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>