<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BST 260 Introduction to Data Science - 19&nbsp; Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./pset2.html" rel="next">
<link href="./18-inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./19-models.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Models</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BST 260 Introduction to Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/datasciencelabs/2023" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course description</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Quarto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-unix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Unix</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Git and GitHub</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-r-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">R Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-vectorization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Vectorization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tidyverse</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-dates-and-times.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dates and times</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-importing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Importing data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-data-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">data.table</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pset1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">ggplot2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-dataviz-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data visualization principles</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Wrangling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-web-scraping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Web scraping</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-locales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Locales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-text-mining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Text mining</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-models.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pset2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 2</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#class-competition" id="toc-class-competition" class="nav-link active" data-scroll-target="#class-competition"><span class="header-section-number">19.1</span> Class competition</a></li>
  <li><a href="#data-driven-models" id="toc-data-driven-models" class="nav-link" data-scroll-target="#data-driven-models"><span class="header-section-number">19.2</span> Data-driven models</a>
  <ul class="collapse">
  <li><a href="#poll-aggregators" id="toc-poll-aggregators" class="nav-link" data-scroll-target="#poll-aggregators"><span class="header-section-number">19.2.1</span> Poll aggregators</a></li>
  <li><a href="#beyond-the-simple-sampling-model" id="toc-beyond-the-simple-sampling-model" class="nav-link" data-scroll-target="#beyond-the-simple-sampling-model"><span class="header-section-number">19.2.2</span> Beyond the simple sampling model</a></li>
  <li><a href="#sec-population-sd" id="toc-sec-population-sd" class="nav-link" data-scroll-target="#sec-population-sd"><span class="header-section-number">19.2.3</span> Estimating the standard deviation</a></li>
  <li><a href="#computing-a-confidence-interval" id="toc-computing-a-confidence-interval" class="nav-link" data-scroll-target="#computing-a-confidence-interval"><span class="header-section-number">19.2.4</span> Computing a confidence interval</a></li>
  <li><a href="#sec-t-dist" id="toc-sec-t-dist" class="nav-link" data-scroll-target="#sec-t-dist"><span class="header-section-number">19.2.5</span> The t-distribution</a></li>
  </ul></li>
  <li><a href="#bayesian-models" id="toc-bayesian-models" class="nav-link" data-scroll-target="#bayesian-models"><span class="header-section-number">19.3</span> Bayesian models</a>
  <ul class="collapse">
  <li><a href="#priors-posteriors-and-and-credible-intervals" id="toc-priors-posteriors-and-and-credible-intervals" class="nav-link" data-scroll-target="#priors-posteriors-and-and-credible-intervals"><span class="header-section-number">19.3.1</span> Priors, posteriors and and credible intervals</a></li>
  </ul></li>
  <li><a href="#hierarchichal-models" id="toc-hierarchichal-models" class="nav-link" data-scroll-target="#hierarchichal-models"><span class="header-section-number">19.4</span> Hierarchichal Models</a>
  <ul class="collapse">
  <li><a href="#case-study-election-forecasting" id="toc-case-study-election-forecasting" class="nav-link" data-scroll-target="#case-study-election-forecasting"><span class="header-section-number">19.4.1</span> Case study: election forecasting</a></li>
  <li><a href="#the-general-bias" id="toc-the-general-bias" class="nav-link" data-scroll-target="#the-general-bias"><span class="header-section-number">19.4.2</span> The general bias</a></li>
  <li><a href="#mathematical-representations-of-the-hierarchical-model" id="toc-mathematical-representations-of-the-hierarchical-model" class="nav-link" data-scroll-target="#mathematical-representations-of-the-hierarchical-model"><span class="header-section-number">19.4.3</span> Mathematical representations of the hierarchical model</a></li>
  <li><a href="#computing-a-posterior-probability" id="toc-computing-a-posterior-probability" class="nav-link" data-scroll-target="#computing-a-posterior-probability"><span class="header-section-number">19.4.4</span> Computing a posterior probability</a></li>
  <li><a href="#predicting-the-electoral-college" id="toc-predicting-the-electoral-college" class="nav-link" data-scroll-target="#predicting-the-electoral-college"><span class="header-section-number">19.4.5</span> Predicting the electoral college</a></li>
  </ul></li>
  <li><a href="#forecasting" id="toc-forecasting" class="nav-link" data-scroll-target="#forecasting"><span class="header-section-number">19.5</span> Forecasting</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">19.6</span> Exercises</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/datasciencelabs/2023/blob/main/19-models.qmd" class="toc-action">View source</a></p><p><a href="https://github.com/datasciencelabs/2023/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<blockquote class="blockquote">
<blockquote class="blockquote">
<p>“All models are wrong, but some are useful.” –George E. P. Box</p>
</blockquote>
</blockquote>
<p>So far, our analysis of poll-related results has been based on a simple sampling model. This model assumes that each voter has an equal chance of being selected for the poll, similar to picking beads from an urn with two colors. However, in this chapter, we explore real-world data and discover that this model is incorrect. Instead, we propose a more effective approach where we directly model the outcomes of pollsters rather than the polls themselves.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="class-competition" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="class-competition"><span class="header-section-number">19.1</span> Class competition</h2>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-2_ca07484778a9149e7427a8e1e149897c">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>clean <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  ret <span class="ot">&lt;-</span> <span class="fu">parse_number</span>(<span class="fu">str_remove</span>(x,<span class="st">"%"</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(ret <span class="sc">&gt;</span> <span class="dv">1</span>, ret<span class="sc">/</span><span class="dv">100</span>, ret)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>odat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"~/Downloads/Poll Competition（回复） - 第 1 张表单回复 (1).csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">"stamp"</span>, <span class="st">"name"</span>, <span class="st">"estimate"</span>, <span class="st">"upper"</span>, <span class="st">"lower"</span>, <span class="st">"n"</span>))  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 31 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): 时间戳记, Name, Prediction, Interval upper bound, Interval lower bound
dbl (1): Sample size

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> odat <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">as.character</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">n</span>())) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(estimate, upper, lower), clean)) <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(estimate <span class="sc">&lt;=</span> <span class="dv">1</span> <span class="sc">&amp;</span> estimate <span class="sc">&gt;</span> <span class="fl">0.2</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(id, estimate, <span class="at">ymin =</span> lower, <span class="at">ymax =</span> upper)) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>() <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.471</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(upper <span class="sc">&gt;=</span> <span class="fl">0.471</span> <span class="sc">&amp;</span> lower <span class="sc">&lt;=</span> <span class="fl">0.471</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">size =</span> upper <span class="sc">-</span> lower) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 8
   stamp                   name          estimate upper lower     n id      size
   &lt;chr&gt;                   &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;
 1 2023-10-11 上午01:14:54 Li Li            0.48  0.5   0.45    100 23    0.05  
 2 2023-10-4 上午11:27:18  Laura Chen       0.45  0.48  0.42     30 3     0.06  
 3 2023-10-4 下午02:20:58  Ellie Zhang      0.450 0.492 0.408   100 5     0.0837
 4 2023-10-4 下午05:29:15  Rachel Sussm…    0.51  0.555 0.465   200 7     0.0906
 5 2023-10-10 下午11:30:30 Yiran Fu         0.5   0.55  0.45     50 15    0.1   
 6 2023-10-10 下午11:44:23 Lindo Nkambu…    0.44  0.524 0.386   200 17    0.138 
 7 2023-10-10 下午10:29:47 Min              0.5   0.57  0.43     30 10    0.14  
 8 2023-10-10 下午11:25:45 Alex Mellott     0.48  0.55  0.41     50 13    0.14  
 9 2023-10-4 下午01:43:59  Camille Shao     0.46  0.55  0.4     300 4     0.15  
10 2023-10-10 下午11:45:31 Zhimeng Liu      0.48  0.6   0.44     25 18    0.16  
11 2023-10-11 上午12:56:12 Dailin Luo       0.5   0.6   0.4      10 22    0.2   
12 2023-10-11 上午07:51:54 Nia Martinez…    0.52  0.71  0.32     15 27    0.39  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="at">estimate =</span><span class="fu">sum</span>(estimate<span class="sc">*</span>n)<span class="sc">/</span><span class="fu">sum</span>(n), <span class="at">n=</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  estimate     n
     &lt;dbl&gt; &lt;dbl&gt;
1    0.487  2020</code></pre>
</div>
</div>
</section>
<section id="data-driven-models" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="data-driven-models"><span class="header-section-number">19.2</span> Data-driven models</h2>
<section id="poll-aggregators" class="level3" data-number="19.2.1">
<h3 data-number="19.2.1" class="anchored" data-anchor-id="poll-aggregators"><span class="header-section-number">19.2.1</span> Poll aggregators</h3>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-4_b305cc23283e683bb2ece830a9070873">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fl">0.039</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>Ns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1298</span>, <span class="dv">533</span>, <span class="dv">1342</span>, <span class="dv">897</span>, <span class="dv">774</span>, <span class="dv">254</span>, <span class="dv">812</span>, <span class="dv">324</span>, <span class="dv">1291</span>, <span class="dv">1056</span>, <span class="dv">2172</span>, <span class="dv">516</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> (mu <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>polls <span class="ot">&lt;-</span> <span class="fu">map_df</span>(Ns, <span class="cf">function</span>(N) {</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">size =</span> N, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> p, p))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  x_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  se_hat <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(x_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> x_hat) <span class="sc">/</span> N)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">estimate =</span> <span class="dv">2</span> <span class="sc">*</span> x_hat <span class="sc">-</span> <span class="dv">1</span>, </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">low =</span> <span class="dv">2</span><span class="sc">*</span>(x_hat <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>se_hat) <span class="sc">-</span> <span class="dv">1</span>, </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">high =</span> <span class="dv">2</span><span class="sc">*</span>(x_hat <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>se_hat) <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_size =</span> N)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>}) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">poll =</span> <span class="fu">seq_along</span>(Ns))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here is a visualization showing the intervals the pollsters would have reported for the difference between Obama and Romney:</p>
<div class="cell" data-hash="19-models_cache/html/simulated-polls_f945342a84fb4ff1046cdcf2c81bd993">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/simulated-polls-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-5_ca579367b83cf3476adcab612e394b4a">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(polls<span class="sc">$</span>sample_size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11269</code></pre>
</div>
</div>
<p>participants. Basically, we construct an estimate of the spread, let’s call it <span class="math inline">\(\mu\)</span>, with a weighted average in the following way:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-6_8421c40ea19d02477ec244ec2c231024">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mu_hat <span class="ot">&lt;-</span> polls <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg =</span> <span class="fu">sum</span>(estimate<span class="sc">*</span>sample_size) <span class="sc">/</span> <span class="fu">sum</span>(sample_size)) <span class="sc">|&gt;</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(avg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Iur margin of error is</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-7_bde531346484fce3d57c0f6cd032245e">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">+</span> mu_hat)<span class="sc">/</span><span class="dv">2</span>; </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>moe <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>(p_hat<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> p_hat)<span class="sc">/</span><span class="fu">sum</span>(polls<span class="sc">$</span>sample_size))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>moe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01845451</code></pre>
</div>
</div>
<p>Thus, we can predict that the spread will be 3.1 plus or minus 1.8, which not only includes the actual result we eventually observed on election night, but is quite far from including 0. Once we combine the 12 polls, we become quite certain that Obama will win the popular vote.</p>
<div class="cell" data-hash="19-models_cache/html/confidence-coverage-2008-election_2e44d68014d432d4d892c625df1f553e">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/confidence-coverage-2008-election-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>However, this was just a simulation to illustrate the idea.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>polls <span class="ot">&lt;-</span> polls_us_election_2016 <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"U.S."</span> <span class="sc">&amp;</span> enddate <span class="sc">&gt;=</span> <span class="st">"2016-10-31"</span> <span class="sc">&amp;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>           (grade <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"A+"</span>,<span class="st">"A"</span>,<span class="st">"A-"</span>,<span class="st">"B+"</span>) <span class="sc">|</span> <span class="fu">is.na</span>(grade)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We add a spread estimate:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-9_d1c0cd1343f65bb9167d23d713b62e2b">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>polls <span class="ot">&lt;-</span> polls <span class="sc">|&gt;</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">spread =</span> rawpoll_clinton<span class="sc">/</span><span class="dv">100</span> <span class="sc">-</span> rawpoll_trump<span class="sc">/</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have 49 estimates of the spread.</p>
<p>The expected value is the election night spread <span class="math inline">\(\mu\)</span> and the standard error is <span class="math inline">\(2\sqrt{p (1 - p) / N}\)</span>. Assuming the urn model we described earlier is a good one, we can use this information to construct a confidence interval based on the aggregated data. The estimated spread is:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-10_3a15021c41ba00bad8f561ca4ba5bb0d">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mu_hat <span class="ot">&lt;-</span> polls <span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mu_hat =</span> <span class="fu">sum</span>(spread <span class="sc">*</span> samplesize) <span class="sc">/</span> <span class="fu">sum</span>(samplesize)) <span class="sc">|&gt;</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(mu_hat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and the standard error is:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-11_7a920af8159d7ce7fe24251b842159c8">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">&lt;-</span> (mu_hat <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">/</span><span class="dv">2</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>moe <span class="ot">&lt;-</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> <span class="fu">sum</span>(polls<span class="sc">$</span>samplesize))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>moe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.006623178</code></pre>
</div>
</div>
<p>So we report a spread of 1.43% with a margin of error of 0.66%. On election night, we discover that the actual percentage was 2.1%, which is outside a 95% confidence interval. What happened?</p>
<p>A histogram of the reported spreads shows a problem:</p>
<div class="cell" data-hash="19-models_cache/html/polls-2016-spread-histogram_1c0a113c46256bba3bcc2b556529a3c9">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>polls <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(spread)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">binwidth =</span> .<span class="dv">01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/polls-2016-spread-histogram-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The data does not appear to be normally distributed and the standard error appears to be larger than 0.0066232. The theory is not working here and in the next section we describe a useful data-driven model.</p>
</section>
<section id="beyond-the-simple-sampling-model" class="level3" data-number="19.2.2">
<h3 data-number="19.2.2" class="anchored" data-anchor-id="beyond-the-simple-sampling-model"><span class="header-section-number">19.2.2</span> Beyond the simple sampling model</h3>
<p>Notice that data come various pollsters and some are taking several polls a week:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-12_2130399a3b60955af7c7e75764c28da5">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>polls <span class="sc">|&gt;</span> <span class="fu">group_by</span>(pollster) <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 2
   pollster                                                   `n()`
   &lt;fct&gt;                                                      &lt;int&gt;
 1 ABC News/Washington Post                                       7
 2 Angus Reid Global                                              1
 3 CBS News/New York Times                                        2
 4 Fox News/Anderson Robbins Research/Shaw &amp; Company Research     2
 5 IBD/TIPP                                                       8
 6 Insights West                                                  1
 7 Ipsos                                                          6
 8 Marist College                                                 1
 9 Monmouth University                                            1
10 Morning Consult                                                1
11 NBC News/Wall Street Journal                                   1
12 RKM Research and Communications, Inc.                          1
13 Selzer &amp; Company                                               1
14 The Times-Picayune/Lucid                                       8
15 USC Dornsife/LA Times                                          8</code></pre>
</div>
</div>
<p>Let’s visualize the data for the pollsters that are regularly polling:</p>
<div class="cell" data-hash="19-models_cache/html/pollster-bias_c8a7499d4f763309e490158541a5b047">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/pollster-bias-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This plot reveals an unexpected result. First, consider that the standard error predicted by theory for each poll is between 0.018 and 0.033:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-13_ba2551f89657b8b77cadc851e88f5f6a">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>polls <span class="sc">|&gt;</span> <span class="fu">group_by</span>(pollster) <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;=</span> <span class="dv">6</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">se =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> <span class="fu">median</span>(samplesize)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  pollster                     se
  &lt;fct&gt;                     &lt;dbl&gt;
1 ABC News/Washington Post 0.0265
2 IBD/TIPP                 0.0333
3 Ipsos                    0.0225
4 The Times-Picayune/Lucid 0.0196
5 USC Dornsife/LA Times    0.0183</code></pre>
</div>
</div>
<p>This agrees with the within poll variation we see. However, there appears to be differences <em>across the polls</em>.</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-14_338e9d9bcecb3201610c6b0df487ddf4">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>one_poll_per_pollster <span class="ot">&lt;-</span> polls <span class="sc">|&gt;</span> <span class="fu">group_by</span>(pollster) <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(enddate <span class="sc">==</span> <span class="fu">max</span>(enddate)) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here is a histogram of the data for these 15 pollsters:</p>
<div class="cell" data-hash="19-models_cache/html/pollster-bias-histogram_ee4dc9cbe2055cccb278afc21e407663">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(spread, <span class="at">data =</span> one_poll_per_pollster, <span class="at">binwidth =</span> <span class="fl">0.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `qplot()` was deprecated in ggplot2 3.4.0.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/pollster-bias-histogram-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Although we are no longer using a model with red (Republicans) and blue (Democrat) beads in an urn, our new model can also be thought of as an urn mode but containing poll results from all possible pollsters and think of our $N=$15 data points</p>
<p><span class="math display">\[X_1,\dots X_N\]</span></p>
<p>a as a random sample from this urn. To develop a useful model, we <em>assume</em> that the expected value of our urn is the actual spread <span class="math inline">\(\mu=2p-1\)</span>, which implies that the sample average has expected value <span class="math inline">\(\mu\)</span>.</p>
<p>Now, because instead of 0s and 1s, our urn contains continuous numbers, the standard deviation of the urn is no longer</p>
<p><span class="math display">\[\sqrt{p(1-p)}\]</span>.</p>
<p>So our new statistical model is that</p>
<p><span class="math display">\[
X_1, \dots, X_N, \text{E}(X) = \mu \text{ and }  \text{SD}(X) = \sigma
\]</span>.</p>
<p>The distribution, for now, is unspecified. But we consider <span class="math inline">\(N\)</span> to be large enough to assume that the sample average</p>
<p><span class="math display">\[
\bar{X} = \sum_{i=1}^N X_i
\]</span></p>
<p>with</p>
<p><span class="math display">\[
\mbox{E}(\bar{X}) = \mu
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\mbox{SE}(\bar{X}) = \sigma / \sqrt{N}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\bar{X} \sim \mbox{N}(\mu, \sigma / \sqrt{N})
\]</span></p>
</section>
<section id="sec-population-sd" class="level3" data-number="19.2.3">
<h3 data-number="19.2.3" class="anchored" data-anchor-id="sec-population-sd"><span class="header-section-number">19.2.3</span> Estimating the standard deviation</h3>
<p>T <span class="math display">\[
s = \sqrt{ \frac{1}{N-1} \sum_{i=1}^N (X_i - \bar{X})^2 }
\]</span></p>
<p>The <code>sd</code> function in R computes the sample standard deviation:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-15_161ddd36ced5bd7434e4de3222d3cbd1">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(one_poll_per_pollster<span class="sc">$</span>spread)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02419369</code></pre>
</div>
</div>
</section>
<section id="computing-a-confidence-interval" class="level3" data-number="19.2.4">
<h3 data-number="19.2.4" class="anchored" data-anchor-id="computing-a-confidence-interval"><span class="header-section-number">19.2.4</span> Computing a confidence interval</h3>
<p>We are now ready to form a new confidence interval based on our new data-driven model:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-16_e10ab6c9319be4f826070658e5933208">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> one_poll_per_pollster <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg =</span> <span class="fu">mean</span>(spread), </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">se =</span> <span class="fu">sd</span>(spread) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(spread))) <span class="sc">|&gt;</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">start =</span> avg <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se, </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">end =</span> avg <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se) </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(results <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  avg  se start end
1 2.9 0.6   1.7 4.1</code></pre>
</div>
</div>
<p>Our confidence interval is wider now since it incorporates the pollster variability. It does include the election night result of 2.1%. Also, note that it was small enough not to include 0, which means we were confident Clinton would win the popular vote.</p>
</section>
<section id="sec-t-dist" class="level3" data-number="19.2.5">
<h3 data-number="19.2.5" class="anchored" data-anchor-id="sec-t-dist"><span class="header-section-number">19.2.5</span> The t-distribution</h3>
<p>The statistic on which confidence intervals for <span class="math inline">\(\mu\)</span> are based is</p>
<p><span class="math display">\[
Z = \frac{\bar{X} - \mu}{\sigma/\sqrt{N}}
\]</span></p>
<p>CLT tells us that Z is approximately normally distributed with expected value 0 and standard error 1. But in practice we don’t know <span class="math inline">\(\sigma\)</span> so we use:</p>
<p><span class="math display">\[
t = \frac{\bar{X} - \mu}{s/\sqrt{N}}
\]</span></p>
<p>This is referred to a <em>t-statistic</em>. By substituting <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span> we introduce some variability. The theory tells us that <span class="math inline">\(t\)</span> follows a <em>student t-distribution</em> with <span class="math inline">\(N-1\)</span> <em>degrees of freedom</em>. The degrees of freedom is a parameter that controls the variability via fatter tails:</p>
<div class="cell" data-hash="19-models_cache/html/t-distribution-examples_04fe3b76dcfefc0dd0e84befe5cc2a7a">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/t-distribution-examples-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>If we are willing to assume the pollster effect data is normally distributed, based on the sample data <span class="math inline">\(X_1, \dots, X_N\)</span>,</p>
<div class="cell" data-hash="19-models_cache/html/poll-spread-qq_bd3f2a8afc28a391f9db621462517113">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>one_poll_per_pollster <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(spread))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/poll-spread-qq-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>then <span class="math inline">\(t\)</span> follows a t-distribution with <span class="math inline">\(N-1\)</span> degrees of freedom. So perhaps a better confidence interval for <span class="math inline">\(\mu\)</span> is:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-18_bd57378e017ef8937d67fe89fd2c62ac">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>,  <span class="fu">nrow</span>(one_poll_per_pollster) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>one_poll_per_pollster <span class="sc">|&gt;</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg =</span> <span class="fu">mean</span>(spread), <span class="at">moe =</span> z<span class="sc">*</span><span class="fu">sd</span>(spread)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(spread))) <span class="sc">|&gt;</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">start =</span> avg <span class="sc">-</span> moe, <span class="at">end =</span> avg <span class="sc">+</span> moe) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
     avg    moe  start    end
   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 0.0290 0.0134 0.0156 0.0424</code></pre>
</div>
</div>
<p>A bit larger than the one using normal is</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-19_c8d343aba5cce199ce67772d9ea0ac5b">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.144787</code></pre>
</div>
</div>
<p>is bigger than</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-20_6e5a3c087f371a8d8b3fe2ce35b72950">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<p>This results in slightly larger confidence interval than we obtained before:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-21_f0ee7d580d14e50f427f62d89b1a8dd5">
<div class="cell-output cell-output-stdout">
<pre><code>  start end
1   1.6 4.2</code></pre>
</div>
</div>
<p>Note that using the t-distribution and the t-statistic is the basis for <em>t-tests</em>, widely used approach for computing p-values. To learn more about t-tests, you can consult any statistics textbook.</p>
<p>The t-distribution can also be used to model errors in bigger deviations that are more likely than with the normal distribution, as seen in the densities we previously saw.</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-22_87bead0e8dec1bed3ac72670b9da8bb3">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>polls_us_election_2016 <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"Wisconsin"</span> <span class="sc">&amp;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>           enddate <span class="sc">&gt;=</span> <span class="st">"2016-10-31"</span> <span class="sc">&amp;</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>           (grade <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"A+"</span>, <span class="st">"A"</span>, <span class="st">"A-"</span>, <span class="st">"B+"</span>) <span class="sc">|</span> <span class="fu">is.na</span>(grade))) <span class="sc">|&gt;</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">spread =</span> rawpoll_clinton<span class="sc">/</span><span class="dv">100</span> <span class="sc">-</span> rawpoll_trump<span class="sc">/</span><span class="dv">100</span>) <span class="sc">|&gt;</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">as.character</span>(state)) <span class="sc">|&gt;</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(results_us_election_2016, <span class="at">by =</span> <span class="st">"state"</span>) <span class="sc">|&gt;</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">actual =</span> clinton<span class="sc">/</span><span class="dv">100</span> <span class="sc">-</span> trump<span class="sc">/</span><span class="dv">100</span>) <span class="sc">|&gt;</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">actual =</span> <span class="fu">first</span>(actual), <span class="at">avg =</span> <span class="fu">mean</span>(spread), </span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(spread), <span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(actual, avg, sd, n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  actual        avg         sd n
1 -0.007 0.07106667 0.01041454 6</code></pre>
</div>
</div>
</section>
</section>
<section id="bayesian-models" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="bayesian-models"><span class="header-section-number">19.3</span> Bayesian models</h2>
<p>In 2016 FiveThirtyEight showed this chart depicting distributions for the percent of the popular vote for each candidate:</p>
<div class="cell" data-hash="19-models_cache/html/fivethirtyeight-densities_50c735f40552321e65a526808c01c874">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="19-models_files/figure-html/fivethirtyeight-densities-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">The colored areas represent values with an 80% chance of including the actual result, according to the FiveThirtyEight model.</figcaption>
</figure>
</div>
</div>
</div>
<p>But what does this mean in the context of the theory we have covered in which these percentages are considered fixed.</p>
<section id="priors-posteriors-and-and-credible-intervals" class="level3" data-number="19.3.1">
<h3 data-number="19.3.1" class="anchored" data-anchor-id="priors-posteriors-and-and-credible-intervals"><span class="header-section-number">19.3.1</span> Priors, posteriors and and credible intervals</h3>
<p>In the previous chapter we an estimate and margin of error for the difference in popular votes between Hillary Clinton and Donald Trump, which we denoted with <span class="math inline">\(\mu\)</span>. The estimate was between 2 and 3 percent and the confidence interval did not include 0. A forecaster would use this to predict Hillary Clinton would win the popular vote. But to make a probabilistic statement about winning the election, we need to use a Bayesian.</p>
<p>We start the Bayesian approach by quantifying our knowledge <em>before</em> seeing any data. This is done using a probability distribution refereed to as a <em>prior</em>. For our example we could write:</p>
<p><span class="math display">\[
\mu \sim N(\theta, \tau)
\]</span></p>
<p>We can think of <span class="math inline">\(\theta\)</span> as our best guess for the popular vote difference had we not seen any polling data and we can think of <span class="math inline">\(\tau\)</span> as quantifying how certain we feel about this guess. Generally, if we have <em>expert knowledge</em> related to <span class="math inline">\(\mu\)</span>, we can try to quantify it with the prior disribution. In the case of election polls, experts use <em>fundamentals</em>, which include, for example, the state of the economy, to develop prior distributions. The data is used to update our initial guess or <em>prior belief</em>. This can be done mathematically if we define the distribution for the observed data, for any given <span class="math inline">\(\mu\)</span>. In our particular example we would write down a model the average of our polls, which is the same as before:</p>
<p><span class="math display">\[
\bar{X} \mid \mu \sim N(\mu, \sigma/\sqrt{N})
\]</span></p>
<p>As before, <span class="math inline">\(\sigma\)</span> describes randomness due to sampling and the pollster effects. In the Bayesian contexts, this is referred to as the sampling distribution. Note that we write the conditional <span class="math inline">\(\bar{X} \mid \mu\)</span> becuase <span class="math inline">\(\mu\)</span> is now considered a random variable.</p>
<p>We do not show the derivations here, but we can now use Calculus and a version fo Bayes Theorem foto derive the distribution of <span class="math inline">\(\mu\)</span> conditional of the data, refered to as the posterior distribution. Specifcially we can show the <span class="math inline">\(\mu \mid \bar{X}\)</span> follows a normal distribution with expected value:</p>
<p><span class="math display">\[
\begin{aligned}
\mbox{E}(\mu \mid \bar{X}) &amp;= B \theta + (1-B) \bar{X}\\
&amp;= \theta + (1-B)(\bar{X}-\theta)\\
\mbox{with } B &amp;= \frac{\sigma^2/N}{\sigma^2/N+\tau^2}
\end{aligned}
\]</span> and standard error :</p>
<p><span class="math display">\[
\mbox{SE}(\mu \mid \bar{X})^2 = \frac{1}{1/\sigma^2+1/\tau^2}.
\]</span></p>
<p>Note that the expected value is a weighted average of our prior guess <span class="math inline">\(\theta\)</span> and the observed data <span class="math inline">\(\bar{X}\)</span>. The weight depends on how certain we are about our prior belief, quantified by <span class="math inline">\(\tau\)</span>, and the precision <span class="math inline">\(\sigma/N\)</span> of the summary of our observed data. This weighted average is sometimes referred to as <em>shrinking</em> because it <em>shrinks</em> estimates towards a prior value.</p>
<p>These quantities useful for updating our beliefs. Specifically, we use the posterior distribution not only to compute the expected value of <span class="math inline">\(\mu\)</span> given the observed data, but for any probability <span class="math inline">\(\alpha\)</span> we can construct intervals, centered at our estimate and with <span class="math inline">\(\alpha\)</span> chance of ocurring.</p>
<p>To compute a posterior distribution and construct a credible interval, we define a prior distribution with mean 0% and standard error 3.5% which can be interpreted as: before seing polling data, we don’t think any candidate has the advantage and a difference of up to 7% either way is possible. We compute the posterior distribution using the equations above:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-25_c9d70b65155b259d4156595391ed46d4">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>theta <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>tau <span class="ot">&lt;-</span> <span class="fl">0.035</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> results<span class="sc">$</span>se</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> results<span class="sc">$</span>avg</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> tau<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>posterior_mean <span class="ot">&lt;-</span> B<span class="sc">*</span>theta <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> B)<span class="sc">*</span>x_bar</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>posterior_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">/</span>sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>tau<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>posterior_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02808534</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>posterior_se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.006149604</code></pre>
</div>
</div>
<p>Because we know the posterior distribution in normal, we can consturct a credible interval like this:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-26_6fdd53ccb7a030400010bbcd2e5ebe99">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>posterior_mean <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span> posterior_se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01603234 0.04013834</code></pre>
</div>
</div>
<p>Furthermore, we can now make the probabilitic statement we could not make with the frequentists approach by computing the posterior probability of Hillary winning the popular vote. Specifically, <span class="math inline">\(\mbox{Pr}(\mu&gt;0 \mid \bar{X})\)</span> can be computed like this:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-27_363bf573b18a5494b319728d9f2dbc88">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">0</span>, posterior_mean, posterior_se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9999975</code></pre>
</div>
</div>
<p>This says we are 100% sure Clinton will win the popular vote, which seems too overconfident. Also, it is not in agreement with FiveThirtyEight’s 81.4%. What explains this difference? There is a level of uncertainty that we are not yet describing, and we will get back to that later.</p>
</section>
</section>
<section id="hierarchichal-models" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="hierarchichal-models"><span class="header-section-number">19.4</span> Hierarchichal Models</h2>
<p>Hierarchical models are useful for quantifying different levels of variability or uncertainty. One can use them using a Bayesian or a Frequentist framework. However because in the Frequentist framework they often extend a model with a fixed parameter by assuming the parameter is actually random, the model description includes two distribution that look like the prior and a sampling distribution used in the Bayesian framework, making the resulting summaries very similar or even equal to what is obtained with a Bayesian context. A key difference between the Bayesian and the Frequentist hierarchical model approach is that in the latter we use data to construct priors rather than treat priors as a quantification of prior expert knowledge. Here illustrate the use of hiereachical models with an example from sports, in which dedicated fans, intuitively apply the ideas of hierarchical models to manage expectations when a new player is of to an exceptionally good start.</p>
<section id="case-study-election-forecasting" class="level3" data-number="19.4.1">
<h3 data-number="19.4.1" class="anchored" data-anchor-id="case-study-election-forecasting"><span class="header-section-number">19.4.1</span> Case study: election forecasting</h3>
<p>Since the 2008 elections, organizations other than FiveThirtyEight have started their own election forecasting groups that also aggregate polling data and uses statistical models to make predictions. However, in 2016 forecasters underestimated Trump’s chances of winning greatly. The day before the election the <em>New York Times</em> <a href="https://www.nytimes.com/interactive/2016/upshot/presidential-polls-forecast.html">reported</a> the following probabilities for Hillary Clinton winning the presidency:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-28_11c139f123075822930b91cc74021813">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">NYT</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">538</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HuffPost</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">PW</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">PEC</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">DK</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Cook</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Roth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Win Prob</td>
<td style="text-align: left;">85%</td>
<td style="text-align: left;">71%</td>
<td style="text-align: left;">98%</td>
<td style="text-align: left;">89%</td>
<td style="text-align: left;">&gt;99%</td>
<td style="text-align: left;">92%</td>
<td style="text-align: left;">Lean Dem</td>
<td style="text-align: left;">Lean Dem</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>For example, the Princeton Election Consortium (PEC) gave Trump less than 1% chance of winning, while the Huffington Post gave him a 2% chance. In contrast, FiveThirtyEight had Trump’s probability of winning at 29%, substantially higher than the others. In fact, four days before the election FiveThirtyEight published an article titled <a href="https://fivethirtyeight.com/features/trump-is-just-a-normal-polling-error-behind-clinton/">Trump Is Just A Normal Polling Error Behind Clinton</a></p>
<p>So why did FiveThirtyEight’s model fair so much better than others? How could PEC and Huffington Post get it so wrong if they were using the same data? In this chapter we describe how FiveThirtyEight used a hierarchical model to correctly account for key sources of variability and outperform all other forecasters. For illustrative purposes we will cotinue examining our popular vote example. In the final section we then describe the more complex approach used to forecast the electoral college result.</p>
</section>
<section id="the-general-bias" class="level3" data-number="19.4.2">
<h3 data-number="19.4.2" class="anchored" data-anchor-id="the-general-bias"><span class="header-section-number">19.4.2</span> The general bias</h3>
<p>In the previous chapter we computed the posterior probability of Hillary Clinton winning the popular vote with a standard Bayesian analysis and found it to be very close to 100%. However, FiveThirtyEight gave her a 81.4% chance[^models-4]. What explains this difference? Below we describe the <em>general bias</em>, another source of variability, included in the <a href="https://projects.fivethirtyeight.com/2016-election-forecast/">FiveThirtyEight model</a>, that accounts for the difference.</p>
<p>After elections are over, one can look at the difference between pollster predictions and actual result. An important observation that our initial models did not take into account is that it is common to see a general bias that affects most pollsters in the same way making the observed data correlated. There is no agreed upon explanation for this, but we do observe it in historical data: in one election, the average of polls favors Democrats by 2%, then in the following election they favor Republicans by 1%, then in the next election there is no bias, then in the following one Republicans are favored by 3%, and so on. In 2016, the polls were biased in favor of the Democrats by 1-2%.</p>
<p>However, although we know this bias term affects our polls, we have no way of knowing what this bias is until election night. So we can’t correct our polls accordingly. What we can do is include a term in our model that accounts for the variability.</p>
</section>
<section id="mathematical-representations-of-the-hierarchical-model" class="level3" data-number="19.4.3">
<h3 data-number="19.4.3" class="anchored" data-anchor-id="mathematical-representations-of-the-hierarchical-model"><span class="header-section-number">19.4.3</span> Mathematical representations of the hierarchical model</h3>
<p>Suppose we are collecting data from one pollster and we assume there is no general bias. The pollster collects several polls with a sample size of <span class="math inline">\(N\)</span>, so we observe several measurements of the spread <span class="math inline">\(X_1, \dots, X_J\)</span>. Suppose the real proportion for Hillary is <span class="math inline">\(p\)</span> and the difference is <span class="math inline">\(\mu\)</span>. The urn model theory tells us that these random variables are normally distributed with expected value <span class="math inline">\(\mu\)</span> and standard error <span class="math inline">\(2 \sqrt{p(1-p)/N}\)</span>:</p>
<p><span class="math display">\[
X_j \sim \mbox{N}\left(\mu, \sqrt{p(1-p)/N}\right)
\]</span></p>
<p>We use the index <span class="math inline">\(j\)</span> to represent the different polls conducted by this pollster. Here is a simulation for six polls assuming the spread is 2.1 and <span class="math inline">\(N\)</span> is 2,000:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-29_ddab3c83b34dd76572acf3104cb68c37">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>J <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> .<span class="dv">021</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> (mu <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(J, mu, <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">/</span> N))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now suppose we have <span class="math inline">\(J=6\)</span> polls from each of <span class="math inline">\(I=5\)</span> different pollsters. For simplicity, let’s say all polls had the same sample size <span class="math inline">\(N\)</span>. The urn model tell us the distribution is the same for all pollsters so to simulate data, we use the same model for each:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-30_5325db79b439819c73bd92b68e811b3e">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>I <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>J <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span>I, <span class="cf">function</span>(i){</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rnorm</span>(J, mu, <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">/</span> N))</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As expected, the simulated data does not really seem to capture the features of the actual data because it does not account for pollster-to-pollster variability:</p>
<div class="cell" data-hash="19-models_cache/html/simulated-data-without-bias_0833268e022fdd118f7d60b69967eb3e">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/simulated-data-without-bias-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To fix this, we need to represent the two levels of variability and we need two indexes, one for pollster and one for the polls each pollster takes. We use <span class="math inline">\(X_{ij}\)</span> with <span class="math inline">\(i\)</span> representing the pollster and <span class="math inline">\(j\)</span> representing the <span class="math inline">\(j\)</span>-th poll from that pollster. The model is now augmented to include pollster effects <span class="math inline">\(h_i\)</span>, referred to as house effects by FiveThirtyEight, with standard deviation <span class="math inline">\(\sigma_h\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
h_i &amp;\sim \mbox{N}\left(0, \sigma_h\right)\\
X_{i,j} \mid h_i &amp;\sim \mbox{N}\left(\mu + h_i, \sqrt{p(1-p)/N}\right)
\end{aligned}
\]</span></p>
<p>To simulate data from a specific pollster, we first need to draw an <span class="math inline">\(h_i\)</span> and the generate individual poll data after adding this effect. Here is how we would do it for one specific pollster. We assume <span class="math inline">\(\sigma_h\)</span> is 0.025:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-31_ecb8b8dd723ae1dcdffd748c133a336d">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>I <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>J <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> .<span class="dv">021</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> (mu <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(I, <span class="dv">0</span>, <span class="fl">0.025</span>)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span>I, <span class="cf">function</span>(i){</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  mu <span class="sc">+</span> h[i] <span class="sc">+</span> <span class="fu">rnorm</span>(J, <span class="dv">0</span>, <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">/</span> N))</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The simulated data now looks more like the actual data:</p>
<div class="cell" data-hash="19-models_cache/html/simulated-pollster-data_dd0e9eeb14b5efc34d2748642e2ed9c4">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/simulated-pollster-data-1.png" class="img-fluid" style="width:35.0%"></p>
</div>
</div>
<p>Note that <span class="math inline">\(h_i\)</span> is common to all the observed spreads from a specific pollster. Different pollsters have a different <span class="math inline">\(h_i\)</span>, which explains why we can see the groups of points shift up and down from pollster to pollster.</p>
<p>Now, in the model above, we assume the average house effect is 0. We think that for every pollster biased in favor of our party, there is another one in favor of the other and assume the standard deviation is <span class="math inline">\(\sigma_h\)</span>. But historically we see that every election has a general bias affecting all polls. We can observe this with the 2016 data, but if we collect historical data, we see that the average of polls misses by more than models like the one above predict. To see this, we would take the average of polls for each election year and compare it to the actual value. If we did this, we would see a difference with a standard deviation of between 2-3%. To incorporate this into the model, we can add another level account for this variability:</p>
<p><span class="math display">\[
\begin{aligned}
b &amp;\sim \mbox{N}\left(0, \sigma_b\right)\\
h_j \mid \, b &amp;\sim \mbox{N}\left(b, \sigma_h\right)\\
X_{i,j} | \, h_j, b &amp;\sim \mbox{N}\left(\mu + h_j, \sqrt{p(1-p)/N}\right)
\end{aligned}
\]</span></p>
<p>This model accounts for three levels of variability: 1) variability in the bias observed from election to election, quantified by <span class="math inline">\(\sigma_b\)</span>, 2) pollster-to-pollster or house effect variability, quantified by <span class="math inline">\(\sigma_h\)</span>, and 3) poll sampling variability, which we can derive to be <span class="math inline">\(\sqrt(p(1-p)/N)\)</span>.</p>
<p>Note that not including a term like <span class="math inline">\(b\)</span> in the models, is what led many forecasters to be overconfident. This random variable changes from election to election, but for any given election, it is the same for all pollsters and polls within on election (note it does not have an index). This implies we can’t estimate <span class="math inline">\(\sigma_h\)</span> with data from just one election. It also implies that the random variables <span class="math inline">\(X_{i,j}\)</span> for a fixed election year share the same <span class="math inline">\(b\)</span> and are therefore correlated.</p>
<p>One way to interpret <span class="math inline">\(b\)</span> is as the difference between the average of all polls from all pollsters and the actual result of the election. Because we don’t know the actual result until after the election, we can’t estimate <span class="math inline">\(b\)</span> until after the election.</p>
</section>
<section id="computing-a-posterior-probability" class="level3" data-number="19.4.4">
<h3 data-number="19.4.4" class="anchored" data-anchor-id="computing-a-posterior-probability"><span class="header-section-number">19.4.4</span> Computing a posterior probability</h3>
<p>Now let’s fit the model above to data. We will use the same data used in the previous chapters and saved in <code>one_poll_per_pollster</code>.</p>
<p>Here we have just one poll per pollster so we will drop the <span class="math inline">\(j\)</span> index and represent the data as before with <span class="math inline">\(X_1, \dots, X_I\)</span>. As a reminder we have data from <span class="math inline">\(I=15\)</span> pollsters. Based on the model assumptions described above, we can mathematically show that the average <span class="math inline">\(\bar{X}\)</span></p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-32_9c0c0266242f75be6967e7210b385eeb">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(one_poll_per_pollster<span class="sc">$</span>spread)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>has expected value <span class="math inline">\(\mu\)</span>, thus it provides an unbiased estimate of the outcome of interest. However, how precise is this estimate? Can we use the observed stample standard deviation to construct an estimate of the standard error of <span class="math inline">\(\bar{X}\)</span>?</p>
<p>It turns out that, because the <span class="math inline">\(X_i\)</span> are correlated, estimating the standard error is more complex than what we have described up to now. Specifically, using advanced statistical calculations not shown here, we can show that the typical variance (standard error squared) estimate</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-33_3dfa9a3a59ac0a520b8149f3c6841db2">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> <span class="fu">with</span>(one_poll_per_pollster, <span class="fu">sd</span>(spread)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">length</span>(spread))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>will consistently underestimate the true standard error by about <span class="math inline">\(\sigma_b^2\)</span>. And, as mentioned earlier, to estimate <span class="math inline">\(\sigma_b\)</span>, we need data from several elections. By collecting and analyzing polling data from several elections, FiveThirtyEight estimates this variability and find that <span class="math inline">\(\sigma_b \approx 0.025\)</span>. We can therefore greatly improve our standard error estimate by adding this quantity:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-34_e12ea24eeb275c43724d9bf6e5e4fba9">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>sigma_b <span class="ot">&lt;-</span> <span class="fl">0.025</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(s2 <span class="sc">+</span> sigma_b<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we redo the Bayesian calculation taking this variability into account, we get a result much closer to FiveThirtyEight’s:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-35_beb87f5584b8d7ecdf2db49d617b4e9b">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>tau <span class="ot">&lt;-</span> <span class="fl">0.035</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> se<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (se<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> tau<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>posterior_mean <span class="ot">&lt;-</span> B<span class="sc">*</span>mu <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>B)<span class="sc">*</span>x_bar</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>posterior_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>( <span class="dv">1</span><span class="sc">/</span> (<span class="dv">1</span><span class="sc">/</span>se<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>tau<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">0</span>, posterior_mean, posterior_se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8174373</code></pre>
</div>
</div>
<p>Note that by accounting for the general bias term, our Bayesian analysis now produces a posterior probability similar to that reported by FiveThirtyEight.</p>
</section>
<section id="predicting-the-electoral-college" class="level3" data-number="19.4.5">
<h3 data-number="19.4.5" class="anchored" data-anchor-id="predicting-the-electoral-college"><span class="header-section-number">19.4.5</span> Predicting the electoral college</h3>
<p>Up to now we have focused on the popular vote. But in the United States, elections are not decided by the popular vote but rather by what is known as the electoral college. Each state gets a number of electoral votes that depends, in a somewhat complex way, on the population size of the state. Here are the top 5 states ranked by electoral votes in 2016.</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-36_9456fd02adcf55868ae728f4a6ce2f88">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>results_us_election_2016 <span class="sc">|&gt;</span> <span class="fu">top_n</span>(<span class="dv">5</span>, electoral_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         state electoral_votes clinton trump others
1   California              55    61.7  31.6    6.7
2        Texas              38    43.2  52.2    4.5
3      Florida              29    47.8  49.0    3.2
4     New York              29    59.0  36.5    4.5
5     Illinois              20    55.8  38.8    5.4
6 Pennsylvania              20    47.9  48.6    3.6</code></pre>
</div>
</div>
<p>With some minor exceptions we don’t discuss, the electoral votes are won all or nothing. For example, if you won California in 2016 by just 1 vote, you still get all 55 of its electoral votes. This means that by winning a few big states by a large margin, but losing many small states by small margins, you can win the popular vote and yet lose the electoral college. This happened in 1876, 1888, 2000, and 2016. The idea behind this is to avoid a few large states having the power to dominate the presidential election.</p>
<div class="callout-not">
<p>Many people in the US consider the electoral college unfair and would like to see it abolished in favor of the popular vote.</p>
</div>
<p>We are now ready to predict the electoral college result for 2016. We start by aggregating results from a poll taken during the last week before the election. We use the <code>grepl</code>, which finds strings in character vectors, to remove polls that are not for entire states.</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-37_cc98fad237ba867533d147e7612dd9b6">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> polls_us_election_2016 <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state<span class="sc">!=</span><span class="st">"U.S."</span> <span class="sc">&amp;</span> </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>           <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"CD"</span>, state) <span class="sc">&amp;</span> </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>           enddate <span class="sc">&gt;=</span><span class="st">"2016-10-31"</span> <span class="sc">&amp;</span> </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>           (grade <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"A+"</span>,<span class="st">"A"</span>,<span class="st">"A-"</span>,<span class="st">"B+"</span>) <span class="sc">|</span> <span class="fu">is.na</span>(grade))) <span class="sc">|&gt;</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">spread =</span> rawpoll_clinton<span class="sc">/</span><span class="dv">100</span> <span class="sc">-</span> rawpoll_trump<span class="sc">/</span><span class="dv">100</span>) <span class="sc">|&gt;</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state) <span class="sc">|&gt;</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg =</span> <span class="fu">mean</span>(spread), <span class="at">sd =</span> <span class="fu">sd</span>(spread), <span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">as.character</span>(state))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the five closest races according to the polls:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-38_60ab290eaaa034144d56b14a91474719">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="fu">abs</span>(avg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 47 × 4
   state               avg     sd     n
   &lt;chr&gt;             &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
 1 Florida         0.00356 0.0163     7
 2 North Carolina -0.0073  0.0306     9
 3 Ohio           -0.0104  0.0252     6
 4 Nevada          0.0169  0.0441     7
 5 Iowa           -0.0197  0.0437     3
 6 Michigan        0.0209  0.0203     6
 7 Arizona        -0.0326  0.0270     9
 8 Pennsylvania    0.0353  0.0116     9
 9 New Mexico      0.0389  0.0226     6
10 Georgia        -0.0448  0.0238     4
# ℹ 37 more rows</code></pre>
</div>
</div>
<p>We now introduce the command <code>left_join</code> that will let us easily add the number of electoral votes for each state from the dataset <code>us_electoral_votes_2016</code>. Here, we simply say that the function combines the two datasets so that the information from the second argument is added to the information in the first:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-39_b3162cf39ebc14e0c030355fda44c3cf">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">left_join</span>(results, results_us_election_2016, <span class="at">by =</span> <span class="st">"state"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that some states have no polls because the winner is pretty much known:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-40_e9b0beea7050a8dbc8382d0da40013b7">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>results_us_election_2016 <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span>state <span class="sc">%in%</span> results<span class="sc">$</span>state) <span class="sc">|&gt;</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Rhode Island"         "Alaska"               "Wyoming"             
[4] "District of Columbia"</code></pre>
</div>
</div>
<p>No polls were conducted in DC, Rhode Island, Alaska, and Wyoming because Democrats are sure to win in the first two and Republicans in the last two.</p>
<p>Because we can’t estimate the standard deviation for states with just one poll, we will estimate it as the median of the standard deviations estimated for states with more than one poll:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-41_1e799ca643919550f1c4a10ea3ae9b81">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> results <span class="sc">|&gt;</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sd =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(sd), <span class="fu">median</span>(results<span class="sc">$</span>sd, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), sd))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To make probabilistic arguments, we will use a Monte Carlo simulation. For each state, we apply the Bayesian approach to generate an election day <span class="math inline">\(\mu\)</span>. We could construct the priors for each state based on recent history. However, to keep it simple, we assign a prior to each state that assumes we know nothing about what will happen. Since from election year to election year the results from a specific state don’t change that much, we will assign a standard deviation of 2% or <span class="math inline">\(\tau=0.02\)</span>. For now, we will assume, incorrectly, that the poll results from each state are independent. The code for the Bayesian calculation under these assumptions looks like this:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-42_4e536a69136c717f4e5adb49e4da740e">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>tau <span class="ot">&lt;-</span> <span class="fl">0.02</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>results <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">sigma =</span> sd<span class="sc">/</span><span class="fu">sqrt</span>(n), </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">B =</span> sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> tau<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">posterior_mean =</span> B <span class="sc">*</span> mu <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> B) <span class="sc">*</span> avg,</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">posterior_se =</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span> (<span class="dv">1</span><span class="sc">/</span>sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>tau<span class="sc">^</span><span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 47 × 12
   state          avg      sd     n electoral_votes clinton trump others   sigma
   &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;           &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1 Alabama   -0.149   2.53e-2     3               9    34.4  62.1    3.6 1.46e-2
 2 Arizona   -0.0326  2.70e-2     9              11    45.1  48.7    6.2 8.98e-3
 3 Arkansas  -0.151   9.90e-4     2               6    33.7  60.6    5.8 7.00e-4
 4 Californ…  0.260   3.87e-2     5              55    61.7  31.6    6.7 1.73e-2
 5 Colorado   0.0452  2.95e-2     7               9    48.2  43.3    8.6 1.11e-2
 6 Connecti…  0.0780  2.11e-2     3               7    54.6  40.9    4.5 1.22e-2
 7 Delaware   0.132   3.35e-2     2               3    53.4  41.9    4.7 2.37e-2
 8 Florida    0.00356 1.63e-2     7              29    47.8  49      3.2 6.18e-3
 9 Georgia   -0.0448  2.38e-2     4              16    45.9  51      3.1 1.19e-2
10 Hawaii     0.186   2.10e-2     1               4    62.2  30      7.7 2.10e-2
# ℹ 37 more rows
# ℹ 3 more variables: B &lt;dbl&gt;, posterior_mean &lt;dbl&gt;, posterior_se &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The estimates based on posterior do move the estimates towards 0, although the states with many polls are influenced less. This is expected as the more poll data we collect, the more we trust those results:</p>
<div class="cell" data-hash="19-models_cache/html/posterior-versus-original-estimates_ce7216869a9fe51f0d97252e17ed3661">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/posterior-versus-original-estimates-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now we repeat this 10,000 times and generate an outcome from the posterior. In each iteration, we keep track of the total number of electoral votes for Clinton. Remember that Trump gets 270 minus the votes for Clinton. Also note that the reason we add 7 in the code is to account for Rhode Island and D.C.:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-43_1f10e9f0e42b6346b218a3f1e13dc60e">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>tau <span class="ot">&lt;-</span> <span class="fl">0.02</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>clinton_EV <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, {</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  results <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">sigma =</span> sd<span class="sc">/</span><span class="fu">sqrt</span>(n), </span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">B =</span> sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> tau<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">posterior_mean =</span> B <span class="sc">*</span> mu <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> B) <span class="sc">*</span> avg,</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">posterior_se =</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span><span class="sc">/</span>sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>tau<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">result =</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(posterior_mean), </span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>                                  posterior_mean, posterior_se),</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">clinton =</span> <span class="fu">ifelse</span>(result <span class="sc">&gt;</span> <span class="dv">0</span>, electoral_votes, <span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">clinton =</span> <span class="fu">sum</span>(clinton)) <span class="sc">|&gt;</span> </span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(clinton) <span class="sc">+</span> <span class="dv">7</span></span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb69-15"><a href="#cb69-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-16"><a href="#cb69-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(clinton_EV <span class="sc">&gt;</span> <span class="dv">269</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.998</code></pre>
</div>
</div>
<p>This model gives Clinton over 99% chance of winning. A similar prediction was made by the Princeton Election Consortium. We now know it was quite off. What happened?</p>
<p>The model above ignores the general bias and assumes the results from different states are independent. After the election, we realized that the general bias in 2016 was not that big: it was between 1 and 2%. But because the election was close in several big states and these states had a large number of polls, pollsters that ignored the general bias greatly underestimated the standard error. Using the notation we introduce, they assumed the standard error was <span class="math inline">\(\sqrt{\sigma^2/N}\)</span> which with large N is quite smaller than the more accurate estimate <span class="math inline">\(\sqrt{\sigma^2/N + \sigma_b^2}\)</span>. FiveThirtyEight, which models the general bias in a rather sophisticated way, reported a closer result. We can simulate the results now with a bias term. For the state level, the general bias can be larger so we set it at <span class="math inline">\(\sigma_b = 0.03\)</span>:</p>
<div class="cell" data-hash="19-models_cache/html/election-forecast-posterior-with-bias, _3855457e8228de87c7f6074c554ebf9d">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>tau <span class="ot">&lt;-</span> <span class="fl">0.02</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>bias_sd <span class="ot">&lt;-</span> <span class="fl">0.03</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>clinton_EV_2 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  results <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">sigma =</span> <span class="fu">sqrt</span>(sd<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n  <span class="sc">+</span> bias_sd<span class="sc">^</span><span class="dv">2</span>),  </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">B =</span> sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> tau<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">posterior_mean =</span> B<span class="sc">*</span>mu <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>B)<span class="sc">*</span>avg,</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">posterior_se =</span> <span class="fu">sqrt</span>( <span class="dv">1</span><span class="sc">/</span> (<span class="dv">1</span><span class="sc">/</span>sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>tau<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">result =</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(posterior_mean), </span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>                                  posterior_mean, posterior_se),</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">clinton =</span> <span class="fu">ifelse</span>(result<span class="sc">&gt;</span><span class="dv">0</span>, electoral_votes, <span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">clinton =</span> <span class="fu">sum</span>(clinton) <span class="sc">+</span> <span class="dv">7</span>) <span class="sc">|&gt;</span> </span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(clinton)</span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(clinton_EV_2 <span class="sc">&gt;</span> <span class="dv">269</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.848</code></pre>
</div>
</div>
<p>This gives us a much more sensible estimate. Looking at the outcomes of the simulation, we see how the bias term adds variability to the final results.</p>
<div class="cell" data-hash="19-models_cache/html/comparison-forecast-with-and-without-bias_b41a979a98598b856a74a33ee7d7dbc4">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/comparison-forecast-with-and-without-bias-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>FiveThirtyEight includes many other features we do not include here. One is that they model variability with distributions that have high probabilities for extreme events compared to the normal. One way we could do this is by changing the distribution used in the simulation from a normal distribution to a t-distribution. FiveThirtyEight predicted a probability of 71%.</p>
</section>
</section>
<section id="forecasting" class="level2" data-number="19.5">
<h2 data-number="19.5" class="anchored" data-anchor-id="forecasting"><span class="header-section-number">19.5</span> Forecasting</h2>
<p>Forecasters like to make predictions well before the election. The predictions are adapted as new polls come out. However, an important question forecasters must ask is: how informative are polls taken several weeks before the election about the actual election? Here we study the variability of poll results across time.</p>
<p>To make sure the variability we observe is not due to pollster effects, let’s study data from one pollster:</p>
<div class="cell" data-hash="19-models_cache/html/poplular-vote-time-trend_600103a47f769348a242c3d0516abbe2">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>one_pollster <span class="ot">&lt;-</span> polls_us_election_2016 <span class="sc">|&gt;</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pollster <span class="sc">==</span> <span class="st">"Ipsos"</span> <span class="sc">&amp;</span> state <span class="sc">==</span> <span class="st">"U.S."</span>) <span class="sc">|&gt;</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">spread =</span> rawpoll_clinton<span class="sc">/</span><span class="dv">100</span> <span class="sc">-</span> rawpoll_trump<span class="sc">/</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since there is no pollster effect, then perhaps the theoretical standard error matches the data-derived standard deviation. We compute both here:</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-44_897144a96931a548ee1161519560f1d5">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> one_pollster <span class="sc">|&gt;</span> </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">empirical =</span> <span class="fu">sd</span>(spread), </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">theoretical =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(spread) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">mean</span>(spread)) <span class="sc">/</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="fu">min</span>(samplesize)))</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   empirical theoretical
1 0.04025194  0.03256719</code></pre>
</div>
</div>
<p>But the empirical standard deviation is higher than the highest possible theoretical estimate. Furthermore, the spread data does not look normal as the theory would predict:</p>
<div class="cell" data-hash="19-models_cache/html/time-trend-variability_bbee0b3b98bef500d62d08e573574a4c">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/time-trend-variability-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The models we have described include pollster-to-pollster variability and sampling error. But this plot is for one pollster and the variability we see is certainly not explained by sampling error. Where is the extra variability coming from? The following plots make a strong case that it comes from time fluctuations not accounted for by the theory that assumes <span class="math inline">\(p\)</span> is fixed:</p>
<div class="cell" data-hash="19-models_cache/html/time-trend-estimate_056adf333349d6276373e5f8a5f4edf3">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/time-trend-estimate-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Some of the peaks and valleys we see coincide with events such as the party conventions, which tend to give the candidate a boost. We can see the peaks and valleys are consistent across several pollsters:</p>
<div class="cell" data-hash="19-models_cache/html/time-trend-estimate-several-pollsters_a059e83fb087942b013ea4aaf54f9e82">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/time-trend-estimate-several-pollsters-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This implies that, if we are going to forecast, our model must include a term to accounts for the time effect. We need to write a model including a bias term for time, denote it <span class="math inline">\(b_t\)</span>. The standard deviation of <span class="math inline">\(b_t\)</span> would depend on <span class="math inline">\(t\)</span> since the closer we get to election day, the closer to 0 this bias term should be.</p>
<p>Pollsters also try to estimate trends from these data and incorporate these into their predictions. We can model the time trend <span class="math inline">\(b_t\)</span> with a smooth function. We usually see the trend estimte not for the difference, but for the actual percentages for each candidate like this:</p>
<div class="cell" data-hash="19-models_cache/html/trend-estimate-for-all-pollsters_0fac43af108c64fa49415580a6fa28da">
<div class="cell-output-display">
<p><img src="19-models_files/figure-html/trend-estimate-for-all-pollsters-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Once a model like the one above is selected, we can use historical and present data to estimate all the necessary parameters to make predictions. There is a variety of methods for estimating trends which we discuss in the Machine Learning part.</p>
</section>
<section id="exercises" class="level2" data-number="19.6">
<h2 data-number="19.6" class="anchored" data-anchor-id="exercises"><span class="header-section-number">19.6</span> Exercises</h2>
<p>We have been using urn models to motivate the use of probability models. Most data science applications are not related to data obtained from urns. More common are data that come from individuals. The reason probability plays a role here is because the data come from a random sample. The random sample is taken from a population and the urn serves as an analogy for the population.</p>
<p>Let’s revisit the heights dataset. Suppose we consider the males in our course the population.</p>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-45_631745045409c4062dc02a08c4224bac">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> heights <span class="sc">|&gt;</span> <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"Male"</span>) <span class="sc">|&gt;</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol class="example" type="1">
<li><p>Mathematically speaking, <code>x</code> is our population. Using the urn analogy, we have an urn with the values of <code>x</code> in it. What are the average and standard deviation of our population?</p></li>
<li><p>Call the population average computed above <span class="math inline">\(\mu\)</span> and the standard deviation <span class="math inline">\(\sigma\)</span>. Now take a sample of size 50, with replacement, and construct an estimate for <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>.</p></li>
<li><p>What does the theory tell us about the sample average <span class="math inline">\(\bar{X}\)</span> and how it is related to <span class="math inline">\(\mu\)</span>?</p></li>
</ol>
<ol type="a">
<li>It is practically identical to <span class="math inline">\(\mu\)</span>.</li>
<li>It is a random variable with expected value <span class="math inline">\(\mu\)</span> and standard error <span class="math inline">\(\sigma/\sqrt{N}\)</span>.</li>
<li>It is a random variable with expected value <span class="math inline">\(\mu\)</span> and standard error <span class="math inline">\(\sigma\)</span>.</li>
<li>Contains no information.</li>
</ol>
<ol start="4" class="example" type="1">
<li><p>So how is this useful? We are going to use an oversimplified yet illustrative example. Suppose we want to know the average height of our male students, but we only get to measure 50 of the 708. We will use <span class="math inline">\(\bar{X}\)</span> as our estimate. We know from the answer to exercise 3 that the standard estimate of our error <span class="math inline">\(\bar{X}-\mu\)</span> is <span class="math inline">\(\sigma/\sqrt{N}\)</span>. We want to compute this, but we don’t know <span class="math inline">\(\sigma\)</span>. Based on what is described in this section, show your estimate of <span class="math inline">\(\sigma\)</span>.</p></li>
<li><p>Now that we have an estimate of <span class="math inline">\(\sigma\)</span>, let’s call our estimate <span class="math inline">\(s\)</span>. Construct a 95% confidence interval for <span class="math inline">\(\mu\)</span>.</p></li>
<li><p>Now run a Monte Carlo simulation in which you compute 10,000 confidence intervals as you have just done. What proportion of these intervals include <span class="math inline">\(\mu\)</span>?</p></li>
<li><p>Use the <code>qnorm</code> and <code>qt</code> functions to generate quantiles. Compare these quantiles for different degrees of freedom for the t-distribution. Use this to motivate the sample size of 30 rule of thumb.</p></li>
<li><p>In 1999, in England, <a href="https://en.wikipedia.org/wiki/Sally_Clark">Sally Clark</a> was found guilty of the murder of two of her sons. Both infants were found dead in the morning, one in 1996 and another in 1998. In both cases, she claimed the cause of death was sudden infant death syndrome (SIDS). No evidence of physical harm was found on the two infants so the main piece of evidence against her was the testimony of Professor Sir Roy Meadow, who testified that the chances of two infants dying of SIDS was 1 in 73 million. He arrived at this figure by finding that the rate of SIDS was 1 in 8,500 and then calculating that the chance of two SIDS cases was 8,500 <span class="math inline">\(\times\)</span> 8,500 <span class="math inline">\(\approx\)</span> 73 million. Which of the following do you agree with?</p></li>
</ol>
<ol type="a">
<li>Sir Meadow assumed that the probability of the second son being affected by SIDS was independent of the first son being affected, thereby ignoring possible genetic causes. If genetics plays a role then: <span class="math inline">\(\mbox{Pr}(\mbox{second case of SIDS} \mid \mbox{first case of SIDS}) &gt; \mbox{P}r(\mbox{first case of SIDS})\)</span>.</li>
<li>Nothing. The multiplication rule always applies in this way: <span class="math inline">\(\mbox{Pr}(A \mbox{ and } B) =\mbox{Pr}(A)\mbox{Pr}(B)\)</span></li>
<li>Sir Meadow is an expert and we should trust his calculations.</li>
<li>Numbers don’t lie.</li>
</ol>
<ol start="9" class="example" type="1">
<li>Until recentely, Florida was one of the most closely watched states in the U.S. election because it has many electoral votes, and the election was generally close, and Florida was a swing state that can vote either way. Create the following table with the polls taken during the last two weeks:</li>
</ol>
<div class="cell" data-hash="19-models_cache/html/unnamed-chunk-46_196152117c68071ddbdeeb2b97e3eaaf">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>polls <span class="ot">&lt;-</span> polls_us_election_2016 <span class="sc">|&gt;</span> </span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"Florida"</span> <span class="sc">&amp;</span> enddate <span class="sc">&gt;=</span> <span class="st">"2016-11-04"</span> ) <span class="sc">|&gt;</span> </span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">spread =</span> rawpoll_clinton<span class="sc">/</span><span class="dv">100</span> <span class="sc">-</span> rawpoll_trump<span class="sc">/</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Take the average spread of these polls. The CLT tells us this average is approximately normal. Calculate an average and provide an estimate of the standard error. Save your results in an object called <code>results</code>.</p>
<ol start="10" class="example" type="1">
<li>Now assume a Bayesian model that sets the prior distribution for Florida’s election night spread <span class="math inline">\(\mu\)</span> to be Normal with expected value <span class="math inline">\(\theta\)</span> and standard deviation <span class="math inline">\(\tau\)</span>. What are the interpretations of <span class="math inline">\(\theta\)</span> and <span class="math inline">\(\tau\)</span>?</li>
</ol>
<ol type="a">
<li><span class="math inline">\(\theta\)</span> and <span class="math inline">\(\tau\)</span> are arbitrary numbers that let us make probability statements about <span class="math inline">\(\mu\)</span>.</li>
<li><span class="math inline">\(\theta\)</span> and <span class="math inline">\(\tau\)</span> summarize what we would predict for Florida before seeing any polls. Based on past elections, we would set <span class="math inline">\(\mu\)</span> close to 0 because both Republicans and Democrats have won, and <span class="math inline">\(\tau\)</span> at about <span class="math inline">\(0.02\)</span>, because these elections tend to be close.</li>
<li><span class="math inline">\(\theta\)</span> and <span class="math inline">\(\tau\)</span> summarize what we want to be true. We therefore set <span class="math inline">\(\theta\)</span> at <span class="math inline">\(0.10\)</span> and <span class="math inline">\(\tau\)</span> at <span class="math inline">\(0.01\)</span>.</li>
<li>The choice of prior has no effect on Bayesian analysis.</li>
</ol>
<ol start="11" class="example" type="1">
<li><p>The CLT tells us that our estimate of the spread <span class="math inline">\(\hat{\mu}\)</span> has normal distribution with expected value <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> calculated in problem 6. Use the formulas we showed for the posterior distribution to calculate the expected value of the posterior distribution if we set <span class="math inline">\(\theta = 0\)</span> and <span class="math inline">\(\tau = 0.01\)</span>.</p></li>
<li><p>Now compute the standard deviation of the posterior distribution.</p></li>
<li><p>Using the fact that the posterior distribution is normal, create an interval that has a 95% probability of occurring centered at the posterior expected value. Note that we call these credible intervals.</p></li>
<li><p>According to this analysis, what was the probability that Trump wins Florida?</p></li>
<li><p>Now use <code>sapply</code> function to change the prior variance from <code>seq(0.005, 0.05, len = 100)</code> and observe how the probability changes by making a plot.</p></li>
<li><p>In April 2013, José Iglesias, a professional baseball player was starting his career. He was performing exceptionally well. Specifically, he had a <em>batting average</em> (AVG) of .450. The batting average statistic is one way of measuring success. Roughly speaking, it tells us the success rate when batting. José had 9 successes out of 20 tries. An AVG of .450 means José has been successful 45% of the times he has batted which is rather high, historically speaking: no one has finished a season with an <code>AVG</code> of .400 or more since Ted Williams did it in 1941! We want to predict José’s batting average at the end of the season after players have about 500 tries or <em>at bats</em>. With the frequentist techniques we have no choice but to predict that his AVG will be .450 at the end of the season. Compute a confidence interval for the success rate.</p></li>
<li><p>Despite the frequentist prediction of <span class="math inline">\(.450\)</span> not a single baseball enthusiast would make this prediction. Why is this? One reason is that they now the estimate has much uncertainty. However, the main reason is that they are implicitly using a hierarchical model that factors in information from years of following baseball. Use the following code to explore the distribution of batting averages in the three seasons prior to 2013 and describe what this tells us.</p></li>
</ol>
<ol start="18" class="example" type="1">
<li><p>So is José lucky or is he the best batter seen in the last 50 years? Perhaps it’s a combination of both luck and talent. But how much of each? If we become convinced that he is lucky, we should trade him to a team that trusts the .450 observation and is maybe overestimating his potential. The hierarchical model provides a mathematical description of how we came to see the observation of .450. First, we pick a player at random with an intrinsic ability summarized by, for example, <span class="math inline">\(\mu\)</span>. Then we see 20 random outcomes with success probability <span class="math inline">\(\mu\)</span>. What model would you use for the first level of your hierarchical model?</p></li>
<li><p>Describe the second level of the hierarchical model.</p></li>
<li><p>Apply the hierarchical model to José’s data. Suppose we want to predict his innate ability in the form of his <em>true</em> batting average <span class="math inline">\(\mu\)</span>. Write down the distributions of the hierarchical model.</p></li>
<li><p>We now are ready to compute a the distribution of <span class="math inline">\(\mu\)</span> conditioned on the observed data <span class="math inline">\(\bar{X}\)</span>. Compute the expected value of <span class="math inline">\(\mu\)</span> given the current average <span class="math inline">\(\bar{X}\)</span> and provide an intuitive explanation for the mathematical formula.</p></li>
<li><p>We started with a frequentist 95% confidence interval that ignored data from other players and summarized just José’s data: .450 <span class="math inline">\(\pm\)</span> 0.220. Construct a credible interval for <span class="math inline">\(\mu\)</span> based on the hierarchical model.</p></li>
<li><p>The credible interval suggests that if another team is impressed by the .450 observation, we should consider trading José as we are predicting he will be just slightly above average. Interestingly, the Red Sox traded José to the Detroit Tigers in July. Here are the José Iglesias batting averages for the next five months:</p></li>
</ol>
<table class="table">
<thead>
<tr class="header">
<th>Month</th>
<th>At Bat</th>
<th>Hits</th>
<th>AVG</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>April</td>
<td>20</td>
<td>9</td>
<td>.450</td>
</tr>
<tr class="even">
<td>May</td>
<td>26</td>
<td>11</td>
<td>.423</td>
</tr>
<tr class="odd">
<td>June</td>
<td>86</td>
<td>34</td>
<td>.395</td>
</tr>
<tr class="even">
<td>July</td>
<td>83</td>
<td>17</td>
<td>.205</td>
</tr>
<tr class="odd">
<td>August</td>
<td>85</td>
<td>25</td>
<td>.294</td>
</tr>
<tr class="even">
<td>September</td>
<td>50</td>
<td>10</td>
<td>.200</td>
</tr>
<tr class="odd">
<td>Total w/o April</td>
<td>330</td>
<td>97</td>
<td>.293</td>
</tr>
</tbody>
</table>
<p>Which of the two approaches provided a better prediciton?</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./18-inference.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./pset2.html" class="pagination-link">
        <span class="nav-page-text">Problem Set 2</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>